#include "topcode.h"
#include "targ_isa_subset.h"
#include "targ_isa_hazards.h"

ISA_HAZARD_INFO ISA_HAZARD_hazard_info[1] = {
  { ISA_HAZARD_UNDEFINED, 0, 0,  0, 0x00, 0 }, /*  0 */
};

mUINT8 ISA_HAZARD_hazard_index[759] = {
    0, /* add       */
    0, /* add_1     */
    0, /* adds      */
    0, /* addl      */
    0, /* addp4     */
    0, /* addp4_i   */
    0, /* alloc_3   */
    0, /* and       */
    0, /* and_i     */
    0, /* andcm     */
    0, /* andcm_i   */
    0, /* br.cond   */
    0, /* br_r.cond */
    0, /* br.call   */
    0, /* br_r.call */
    0, /* br.ret    */
    0, /* br.ia     */
    0, /* br.cloop  */
    0, /* br.ctop   */
    0, /* br.cexit  */
    0, /* br.wtop   */
    0, /* br.wexit  */
    0, /* break.i   */
    0, /* break.b   */
    0, /* break.m   */
    0, /* break.f   */
    0, /* break.x   */
    0, /* brl.cond  */
    0, /* brl.call  */
    0, /* brp       */
    0, /* brp_r     */
    0, /* brp.ret   */
    0, /* bsw.0     */
    0, /* bsw.1     */
    0, /* chk.s.i   */
    0, /* chk.s.m   */
    0, /* chk_f.s   */
    0, /* chk.a     */
    0, /* chk_f.a   */
    0, /* clrrrb    */
    0, /* clrrrb.pr */
    0, /* cmp.eq    */
    0, /* cmp.eq.unc */
    0, /* cmp.eq.and */
    0, /* cmp.eq.or */
    0, /* cmp.eq.or.andcm */
    0, /* cmp.ne.and */
    0, /* cmp.ne.or */
    0, /* cmp.ne.or.andcm */
    0, /* cmp.lt    */
    0, /* cmp.lt.unc */
    0, /* cmp.ltu   */
    0, /* cmp.ltu.unc */
    0, /* cmp_z1.lt.and */
    0, /* cmp_z1.lt.or */
    0, /* cmp_z1.lt.or.andcm */
    0, /* cmp_z1.le.and */
    0, /* cmp_z1.le.or */
    0, /* cmp_z1.le.or.andcm */
    0, /* cmp_z1.gt.and */
    0, /* cmp_z1.gt.or */
    0, /* cmp_z1.gt.or.andcm */
    0, /* cmp_z1.ge.and */
    0, /* cmp_z1.ge.or */
    0, /* cmp_z1.ge.or.andcm */
    0, /* cmp_i.eq  */
    0, /* cmp_i.eq.unc */
    0, /* cmp_i.eq.and */
    0, /* cmp_i.eq.or */
    0, /* cmp_i.eq.or.andcm */
    0, /* cmp_i.ne.and */
    0, /* cmp_i.ne.or */
    0, /* cmp_i.ne.or.andcm */
    0, /* cmp_i.lt  */
    0, /* cmp_i.lt.unc */
    0, /* cmp_i.ltu */
    0, /* cmp_i.ltu.unc */
    0, /* cmp4.eq   */
    0, /* cmp4.eq.unc */
    0, /* cmp4.eq.and */
    0, /* cmp4.eq.or */
    0, /* cmp4.eq.or.andcm */
    0, /* cmp4.ne.and */
    0, /* cmp4.ne.or */
    0, /* cmp4.ne.or.andcm */
    0, /* cmp4.lt   */
    0, /* cmp4.lt.unc */
    0, /* cmp4.ltu  */
    0, /* cmp4.ltu.unc */
    0, /* cmp4_z1.lt.and */
    0, /* cmp4_z1.lt.or */
    0, /* cmp4_z1.lt.or.andcm */
    0, /* cmp4_z1.le.and */
    0, /* cmp4_z1.le.or */
    0, /* cmp4_z1.le.or.andcm */
    0, /* cmp4_z1.gt.and */
    0, /* cmp4_z1.gt.or */
    0, /* cmp4_z1.gt.or.andcm */
    0, /* cmp4_z1.ge.and */
    0, /* cmp4_z1.ge.or */
    0, /* cmp4_z1.ge.or.andcm */
    0, /* cmp4_i.eq */
    0, /* cmp4_i.eq.unc */
    0, /* cmp4_i.eq.and */
    0, /* cmp4_i.eq.or */
    0, /* cmp4_i.eq.or.andcm */
    0, /* cmp4_i.ne.and */
    0, /* cmp4_i.ne.or */
    0, /* cmp4_i.ne.or.andcm */
    0, /* cmp4_i.lt */
    0, /* cmp4_i.lt.unc */
    0, /* cmp4_i.ltu */
    0, /* cmp4_i.ltu.unc */
    0, /* cmpxchg1  */
    0, /* cmpxchg2  */
    0, /* cmpxchg4  */
    0, /* cmpxchg8  */
    0, /* cover     */
    0, /* czx1.l    */
    0, /* czx1.r    */
    0, /* czx2.l    */
    0, /* czx2.r    */
    0, /* dep       */
    0, /* dep.z     */
    0, /* dep_i     */
    0, /* dep_i.z   */
    0, /* epc       */
    0, /* extr      */
    0, /* extr.u    */
    0, /* famax     */
    0, /* famin     */
    0, /* fand      */
    0, /* fandcm    */
    0, /* fc        */
    0, /* fchkf     */
    0, /* fclass.m  */
    0, /* fclass.m.unc */
    0, /* fclrf     */
    0, /* fcmp.eq   */
    0, /* fcmp.eq.unc */
    0, /* fcmp.lt   */
    0, /* fcmp.lt.unc */
    0, /* fcmp.le   */
    0, /* fcmp.le.unc */
    0, /* fcmp.unord */
    0, /* fcmp.unord.unc */
    0, /* fcvt.fx   */
    0, /* fcvt.fx.trunc */
    0, /* fcvt.fxu  */
    0, /* fcvt.fxu.trunc */
    0, /* fcvt.xf   */
    0, /* fetchadd4 */
    0, /* fetchadd8 */
    0, /* flushrs   */
    0, /* fma       */
    0, /* fma.s     */
    0, /* fma.d     */
    0, /* fmax      */
    0, /* fmerge.ns */
    0, /* fmerge.s  */
    0, /* fmerge.se */
    0, /* fmin      */
    0, /* fmix.l    */
    0, /* fmix.r    */
    0, /* fmix.lr   */
    0, /* fms       */
    0, /* fms.s     */
    0, /* fms.d     */
    0, /* fnma      */
    0, /* fnma.s    */
    0, /* fnma.d    */
    0, /* for       */
    0, /* fpack     */
    0, /* fpamax    */
    0, /* fpamin    */
    0, /* fpcmp.eq  */
    0, /* fpcmp.lt  */
    0, /* fpcmp.le  */
    0, /* fpcmp.unord */
    0, /* fpcmp.neq */
    0, /* fpcmp.nlt */
    0, /* fpcmp.nle */
    0, /* fpcmp.ord */
    0, /* fpcvt.fx  */
    0, /* fpcvt.fx.trunc */
    0, /* fpcvt.fxu */
    0, /* fpcvt.fxu.trunc */
    0, /* fpma      */
    0, /* fpmax     */
    0, /* fpmerge.ns */
    0, /* fpmerge.s */
    0, /* fpmerge.se */
    0, /* fpmin     */
    0, /* fpms      */
    0, /* fpnma     */
    0, /* fprcpa    */
    0, /* fprsqrta  */
    0, /* frcpa     */
    0, /* frsqrta   */
    0, /* fselect   */
    0, /* fsetc     */
    0, /* fswap     */
    0, /* fswap.nl  */
    0, /* fswap.nr  */
    0, /* fsxt.l    */
    0, /* fsxt.r    */
    0, /* fwb       */
    0, /* fxor      */
    0, /* getf.s    */
    0, /* getf.d    */
    0, /* getf.exp  */
    0, /* getf.sig  */
    0, /* invala    */
    0, /* invala.e  */
    0, /* invala_f.e */
    0, /* itc.i     */
    0, /* itc.d     */
    0, /* itr.i     */
    0, /* itr.d     */
    0, /* ld1       */
    0, /* ld1_r     */
    0, /* ld1_i     */
    0, /* ld2       */
    0, /* ld2_r     */
    0, /* ld2_i     */
    0, /* ld4       */
    0, /* ld4_r     */
    0, /* ld4_i     */
    0, /* ld8       */
    0, /* ld8_r     */
    0, /* ld8_i     */
    0, /* ld8.fill  */
    0, /* ld8_r.fill */
    0, /* ld8_i.fill */
    0, /* ldfs      */
    0, /* ldfs_r    */
    0, /* ldfs_i    */
    0, /* ldfd      */
    0, /* ldfd_r    */
    0, /* ldfd_i    */
    0, /* ldfe      */
    0, /* ldfe_r    */
    0, /* ldfe_i    */
    0, /* ldf8      */
    0, /* ldf8_r    */
    0, /* ldf8_i    */
    0, /* ldf.fill  */
    0, /* ldf_r.fill */
    0, /* ldf_i.fill */
    0, /* ldfps     */
    0, /* ldfps_i   */
    0, /* ldfpd     */
    0, /* ldfpd_i   */
    0, /* ldfp8     */
    0, /* ldfp8_i   */
    0, /* lfetch    */
    0, /* lfetch.excl */
    0, /* lfetch.fault */
    0, /* lfetch.fault.excl */
    0, /* lfetch_r  */
    0, /* lfetch_r.excl */
    0, /* lfetch_r.fault */
    0, /* lfetch_r.fault.excl */
    0, /* lfetch_i  */
    0, /* lfetch_i.excl */
    0, /* lfetch_i.fault */
    0, /* lfetch_i.fault.excl */
    0, /* loadrs    */
    0, /* mf        */
    0, /* mf.a      */
    0, /* mix1.l    */
    0, /* mix1.r    */
    0, /* mix2.l    */
    0, /* mix2.r    */
    0, /* mix4.l    */
    0, /* mix4.r    */
    0, /* mov_f_ar.i */
    0, /* mov_t_ar_r.i */
    0, /* mov_t_ar_i.i */
    0, /* mov_f_ar.m */
    0, /* mov_t_ar_r.m */
    0, /* mov_t_ar_i.m */
    0, /* mov_f_br  */
    0, /* mov_t_br_i */
    0, /* mov_t_br.ret */
    0, /* mov_t_cr  */
    0, /* mov_f_cr  */
    0, /* mov_f_cpuid */
    0, /* mov_t_dbr */
    0, /* mov_f_dbr */
    0, /* mov_t_ibr */
    0, /* mov_f_ibr */
    0, /* mov_t_msr */
    0, /* mov_f_msr */
    0, /* mov_t_pkr */
    0, /* mov_f_pkr */
    0, /* mov_t_pmc */
    0, /* mov_f_pmc */
    0, /* mov_t_pmd */
    0, /* mov_f_pmd */
    0, /* mov_t_rr  */
    0, /* mov_f_rr  */
    0, /* mov_f_ip  */
    0, /* mov_f_pr  */
    0, /* mov_t_pr  */
    0, /* mov_t_pr_i */
    0, /* mov_t_psr */
    0, /* mov_f_psr */
    0, /* mov_t_psrum */
    0, /* mov_f_psrum */
    0, /* movl      */
    0, /* mux1      */
    0, /* mux2      */
    0, /* nop.i     */
    0, /* nop.b     */
    0, /* nop.m     */
    0, /* nop.f     */
    0, /* nop.x     */
    0, /* or        */
    0, /* or_i      */
    0, /* pack2.sss */
    0, /* pack2.uss */
    0, /* pack4.sss */
    0, /* padd1     */
    0, /* padd1.sss */
    0, /* padd1.uus */
    0, /* padd1.uuu */
    0, /* padd2     */
    0, /* padd2.sss */
    0, /* padd2.uus */
    0, /* padd2.uuu */
    0, /* padd4     */
    0, /* pavg1     */
    0, /* pavg1.raz */
    0, /* pavg2     */
    0, /* pavg2.raz */
    0, /* pavgsub1  */
    0, /* pavgsub2  */
    0, /* pcmp1.eq  */
    0, /* pcmp1.gt  */
    0, /* pcmp2.eq  */
    0, /* pcmp2.gt  */
    0, /* pcmp4.eq  */
    0, /* pcmp4.gt  */
    0, /* pmax1.u   */
    0, /* pmax2     */
    0, /* pmin1.u   */
    0, /* pmin2     */
    0, /* pmpy2.r   */
    0, /* pmpy2.l   */
    0, /* pmpyshr2  */
    0, /* pmpyshr2.u */
    0, /* popcnt    */
    0, /* probe.r   */
    0, /* probe.w   */
    0, /* probe_i.r */
    0, /* probe_i.w */
    0, /* probe.r.fault */
    0, /* probe.w.fault */
    0, /* probe.rw.fault */
    0, /* psad1     */
    0, /* pshl2     */
    0, /* pshl4     */
    0, /* pshl2_i   */
    0, /* pshl4_i   */
    0, /* pshladd2  */
    0, /* pshr2     */
    0, /* pshr2.u   */
    0, /* pshr4     */
    0, /* pshr4.u   */
    0, /* pshr2_i   */
    0, /* pshr2_i.u */
    0, /* pshr4_i   */
    0, /* pshr4_i.u */
    0, /* pshradd2  */
    0, /* psub1     */
    0, /* psub2     */
    0, /* psub4     */
    0, /* psub1.sss */
    0, /* psub1.uus */
    0, /* psub1.uuu */
    0, /* psub2.sss */
    0, /* psub2.uus */
    0, /* psub2.uuu */
    0, /* ptc.e     */
    0, /* ptc.g     */
    0, /* ptc.ga    */
    0, /* ptc.l     */
    0, /* ptr.d     */
    0, /* ptr.i     */
    0, /* rfi       */
    0, /* rsm       */
    0, /* rum       */
    0, /* setf.s    */
    0, /* setf.d    */
    0, /* setf.exp  */
    0, /* setf.sig  */
    0, /* shl       */
    0, /* shladd    */
    0, /* shladdp4  */
    0, /* shr       */
    0, /* shr.u     */
    0, /* shrp      */
    0, /* srlz.i    */
    0, /* srlz.d    */
    0, /* ssm       */
    0, /* st1       */
    0, /* st1_i     */
    0, /* st2       */
    0, /* st2_i     */
    0, /* st4       */
    0, /* st4_i     */
    0, /* st8       */
    0, /* st8_i     */
    0, /* st8.spill */
    0, /* st8_i.spill */
    0, /* stfs      */
    0, /* stfs_i    */
    0, /* stfd      */
    0, /* stfd_i    */
    0, /* stfe      */
    0, /* stfe_i    */
    0, /* stf8      */
    0, /* stf8_i    */
    0, /* stf.spill */
    0, /* stf_i.spill */
    0, /* sub       */
    0, /* sub_1     */
    0, /* sub_i     */
    0, /* sum       */
    0, /* sxt1      */
    0, /* sxt2      */
    0, /* sxt4      */
    0, /* sync.i    */
    0, /* tak       */
    0, /* tbit.z    */
    0, /* tbit.z.unc */
    0, /* tbit.z.and */
    0, /* tbit.z.or */
    0, /* tbit.z.or.andcm */
    0, /* tbit.nz.and */
    0, /* tbit.nz.or */
    0, /* tbit.nz.or.andcm */
    0, /* thash     */
    0, /* tnat.z    */
    0, /* tnat.z.unc */
    0, /* tnat.z.and */
    0, /* tnat.z.or */
    0, /* tnat.z.or.andcm */
    0, /* tnat.nz.and */
    0, /* tnat.nz.or */
    0, /* tnat.nz.or.andcm */
    0, /* tpa       */
    0, /* ttag      */
    0, /* unpack1.l */
    0, /* unpack1.h */
    0, /* unpack2.l */
    0, /* unpack2.h */
    0, /* unpack4.l */
    0, /* unpack4.h */
    0, /* xchg1     */
    0, /* xchg2     */
    0, /* xchg4     */
    0, /* xchg8     */
    0, /* xma.l     */
    0, /* xma.h     */
    0, /* xma.hu    */
    0, /* xor       */
    0, /* xor_i     */
    0, /* zxt1      */
    0, /* zxt2      */
    0, /* zxt4      */
    0, /* alloc     */
    0, /* br        */
    0, /* br_r      */
    0, /* brl       */
    0, /* cmp.eq.orcm */
    0, /* cmp.eq.andcm */
    0, /* cmp.eq.and.orcm */
    0, /* cmp.ne    */
    0, /* cmp.ne.unc */
    0, /* cmp.ne.orcm */
    0, /* cmp.ne.andcm */
    0, /* cmp.ne.and.orcm */
    0, /* cmp.le    */
    0, /* cmp.le.unc */
    0, /* cmp.gt    */
    0, /* cmp.gt.unc */
    0, /* cmp.ge    */
    0, /* cmp.ge.unc */
    0, /* cmp.leu   */
    0, /* cmp.leu.unc */
    0, /* cmp.gtu   */
    0, /* cmp.gtu.unc */
    0, /* cmp.geu   */
    0, /* cmp.geu.unc */
    0, /* cmp_z1.lt.orcm */
    0, /* cmp_z1.lt.andcm */
    0, /* cmp_z1.lt.and.orcm */
    0, /* cmp_z1.le.orcm */
    0, /* cmp_z1.le.andcm */
    0, /* cmp_z1.le.and.orcm */
    0, /* cmp_z1.gt.orcm */
    0, /* cmp_z1.gt.andcm */
    0, /* cmp_z1.gt.and.orcm */
    0, /* cmp_z1.ge.orcm */
    0, /* cmp_z1.ge.andcm */
    0, /* cmp_z1.ge.and.orcm */
    0, /* cmp_z2.lt.orcm */
    0, /* cmp_z2.lt.andcm */
    0, /* cmp_z2.lt.and.orcm */
    0, /* cmp_z2.le.orcm */
    0, /* cmp_z2.le.andcm */
    0, /* cmp_z2.le.and.orcm */
    0, /* cmp_z2.gt.orcm */
    0, /* cmp_z2.gt.andcm */
    0, /* cmp_z2.gt.and.orcm */
    0, /* cmp_z2.ge.orcm */
    0, /* cmp_z2.ge.andcm */
    0, /* cmp_z2.ge.and.orcm */
    0, /* cmp_z2.lt.and */
    0, /* cmp_z2.lt.or */
    0, /* cmp_z2.lt.or.andcm */
    0, /* cmp_z2.le.and */
    0, /* cmp_z2.le.or */
    0, /* cmp_z2.le.or.andcm */
    0, /* cmp_z2.gt.and */
    0, /* cmp_z2.gt.or */
    0, /* cmp_z2.gt.or.andcm */
    0, /* cmp_z2.ge.and */
    0, /* cmp_z2.ge.or */
    0, /* cmp_z2.ge.or.andcm */
    0, /* cmp_i.eq.orcm */
    0, /* cmp_i.eq.andcm */
    0, /* cmp_i.eq.and.orcm */
    0, /* cmp_i.ne  */
    0, /* cmp_i.ne.unc */
    0, /* cmp_i.ne.orcm */
    0, /* cmp_i.ne.andcm */
    0, /* cmp_i.ne.and.orcm */
    0, /* cmp_i.le  */
    0, /* cmp_i.le.unc */
    0, /* cmp_i.gt  */
    0, /* cmp_i.gt.unc */
    0, /* cmp_i.ge  */
    0, /* cmp_i.ge.unc */
    0, /* cmp_i.leu */
    0, /* cmp_i.leu.unc */
    0, /* cmp_i.gtu */
    0, /* cmp_i.gtu.unc */
    0, /* cmp_i.geu */
    0, /* cmp_i.geu.unc */
    0, /* cmp4.eq.orcm */
    0, /* cmp4.eq.andcm */
    0, /* cmp4.eq.and.orcm */
    0, /* cmp4.ne   */
    0, /* cmp4.ne.unc */
    0, /* cmp4.ne.orcm */
    0, /* cmp4.ne.andcm */
    0, /* cmp4.ne.and.orcm */
    0, /* cmp4.le   */
    0, /* cmp4.le.unc */
    0, /* cmp4.gt   */
    0, /* cmp4.gt.unc */
    0, /* cmp4.ge   */
    0, /* cmp4.ge.unc */
    0, /* cmp4.leu  */
    0, /* cmp4.leu.unc */
    0, /* cmp4.gtu  */
    0, /* cmp4.gtu.unc */
    0, /* cmp4.geu  */
    0, /* cmp4.geu.unc */
    0, /* cmp4_z1.lt.orcm */
    0, /* cmp4_z1.lt.andcm */
    0, /* cmp4_z1.lt.and.orcm */
    0, /* cmp4_z1.le.orcm */
    0, /* cmp4_z1.le.andcm */
    0, /* cmp4_z1.le.and.orcm */
    0, /* cmp4_z1.gt.orcm */
    0, /* cmp4_z1.gt.andcm */
    0, /* cmp4_z1.gt.and.orcm */
    0, /* cmp4_z1.ge.orcm */
    0, /* cmp4_z1.ge.andcm */
    0, /* cmp4_z1.ge.and.orcm */
    0, /* cmp4_z2.lt.orcm */
    0, /* cmp4_z2.lt.andcm */
    0, /* cmp4_z2.lt.and.orcm */
    0, /* cmp4_z2.le.orcm */
    0, /* cmp4_z2.le.andcm */
    0, /* cmp4_z2.le.and.orcm */
    0, /* cmp4_z2.gt.orcm */
    0, /* cmp4_z2.gt.andcm */
    0, /* cmp4_z2.gt.and.orcm */
    0, /* cmp4_z2.ge.orcm */
    0, /* cmp4_z2.ge.andcm */
    0, /* cmp4_z2.ge.and.orcm */
    0, /* cmp4_z2.lt.and */
    0, /* cmp4_z2.lt.or */
    0, /* cmp4_z2.lt.or.andcm */
    0, /* cmp4_z2.le.and */
    0, /* cmp4_z2.le.or */
    0, /* cmp4_z2.le.or.andcm */
    0, /* cmp4_z2.gt.and */
    0, /* cmp4_z2.gt.or */
    0, /* cmp4_z2.gt.or.andcm */
    0, /* cmp4_z2.ge.and */
    0, /* cmp4_z2.ge.or */
    0, /* cmp4_z2.ge.or.andcm */
    0, /* cmp4_i.eq.orcm */
    0, /* cmp4_i.eq.andcm */
    0, /* cmp4_i.eq.and.orcm */
    0, /* cmp4_i.ne */
    0, /* cmp4_i.ne.unc */
    0, /* cmp4_i.ne.orcm */
    0, /* cmp4_i.ne.andcm */
    0, /* cmp4_i.ne.and.orcm */
    0, /* cmp4_i.le */
    0, /* cmp4_i.le.unc */
    0, /* cmp4_i.gt */
    0, /* cmp4_i.gt.unc */
    0, /* cmp4_i.ge */
    0, /* cmp4_i.ge.unc */
    0, /* cmp4_i.leu */
    0, /* cmp4_i.leu.unc */
    0, /* cmp4_i.gtu */
    0, /* cmp4_i.gtu.unc */
    0, /* cmp4_i.geu */
    0, /* cmp4_i.geu.unc */
    0, /* fabs      */
    0, /* fadd      */
    0, /* fadd.s    */
    0, /* fadd.d    */
    0, /* fclass.nm */
    0, /* fclass.nm.unc */
    0, /* fcmp.gt   */
    0, /* fcmp.gt.unc */
    0, /* fcmp.ge   */
    0, /* fcmp.ge.unc */
    0, /* fcmp.neq  */
    0, /* fcmp.neq.unc */
    0, /* fcmp.nlt  */
    0, /* fcmp.nlt.unc */
    0, /* fcmp.nle  */
    0, /* fcmp.nle.unc */
    0, /* fcmp.ngt  */
    0, /* fcmp.ngt.unc */
    0, /* fcmp.nge  */
    0, /* fcmp.nge.unc */
    0, /* fcmp.ord  */
    0, /* fcmp.ord.unc */
    0, /* fcvt.xuf  */
    0, /* fcvt.xuf.s */
    0, /* fcvt.xuf.d */
    0, /* fmpy      */
    0, /* fmpy.s    */
    0, /* fmpy.d    */
    0, /* fneg      */
    0, /* fnegabs   */
    0, /* fnmpy     */
    0, /* fnmpy.s   */
    0, /* fnmpy.d   */
    0, /* fnorm     */
    0, /* fnorm.s   */
    0, /* fnorm.d   */
    0, /* fpabs     */
    0, /* fpcmp.gt  */
    0, /* fpcmp.ge  */
    0, /* fpcmp.ngt */
    0, /* fpcmp.nge */
    0, /* fpmpy     */
    0, /* fpneg     */
    0, /* fpnegabs  */
    0, /* fpnmpy    */
    0, /* fsub      */
    0, /* fsub.s    */
    0, /* fsub.d    */
    0, /* mov_t_br  */
    0, /* mov_f     */
    0, /* mov       */
    0, /* mov_i     */
    0, /* shl_i     */
    0, /* shr_i     */
    0, /* shr_i.u   */
    0, /* tbit.nz   */
    0, /* tbit.nz.unc */
    0, /* tnat.nz   */
    0, /* tnat.nz.unc */
    0, /* xma.lu    */
    0, /* xmpy.l    */
    0, /* xmpy.lu   */
    0, /* xmpy.h    */
    0, /* xmpy.hu   */
    0, /* break     */
    0, /* chk.s     */
    0, /* cmp.lt.and */
    0, /* cmp.lt.or */
    0, /* cmp.lt.or.andcm */
    0, /* cmp.le.and */
    0, /* cmp.le.or */
    0, /* cmp.le.or.andcm */
    0, /* cmp.gt.and */
    0, /* cmp.gt.or */
    0, /* cmp.gt.or.andcm */
    0, /* cmp.ge.and */
    0, /* cmp.ge.or */
    0, /* cmp.ge.or.andcm */
    0, /* cmp.lt.orcm */
    0, /* cmp.lt.andcm */
    0, /* cmp.lt.and.orcm */
    0, /* cmp.le.orcm */
    0, /* cmp.le.andcm */
    0, /* cmp.le.and.orcm */
    0, /* cmp.gt.orcm */
    0, /* cmp.gt.andcm */
    0, /* cmp.gt.and.orcm */
    0, /* cmp.ge.orcm */
    0, /* cmp.ge.andcm */
    0, /* cmp.ge.and.orcm */
    0, /* cmp4.lt.and */
    0, /* cmp4.lt.or */
    0, /* cmp4.lt.or.andcm */
    0, /* cmp4.le.and */
    0, /* cmp4.le.or */
    0, /* cmp4.le.or.andcm */
    0, /* cmp4.gt.and */
    0, /* cmp4.gt.or */
    0, /* cmp4.gt.or.andcm */
    0, /* cmp4.ge.and */
    0, /* cmp4.ge.or */
    0, /* cmp4.ge.or.andcm */
    0, /* cmp4.lt.orcm */
    0, /* cmp4.lt.andcm */
    0, /* cmp4.lt.and.orcm */
    0, /* cmp4.le.orcm */
    0, /* cmp4.le.andcm */
    0, /* cmp4.le.and.orcm */
    0, /* cmp4.gt.orcm */
    0, /* cmp4.gt.andcm */
    0, /* cmp4.gt.and.orcm */
    0, /* cmp4.ge.orcm */
    0, /* cmp4.ge.andcm */
    0, /* cmp4.ge.and.orcm */
    0, /* mov_f_ar  */
    0, /* mov_t_ar_r */
    0, /* mov_t_ar_i */
    0, /* nop       */
    0, /* asm       */
    0, /* intrncall */
    0, /* spadjust  */
    0, /* copy.br   */
    0, /* begin.pregtn */
    0, /* end.pregtn */
    0, /* bwd.bar   */
    0, /* fwd.bar   */
    0, /* dfixup    */
    0, /* ffixup    */
    0, /* ifixup    */
    0, /* label     */
    0, /* noop      */
};

void ISA_HAZARD_Initialize(void)
{
  INT top;
  INT mask = 1 << (INT)ISA_SUBSET_Value;
  for ( top = 0; top < TOP_count; ++top ) {
    INT j, k;
    INT i = ISA_HAZARD_hazard_index[top];
    for (j = i; j != 0; j = k) {
      for (k = ISA_HAZARD_hazard_info[j].next;
           k != 0 && (ISA_HAZARD_hazard_info[k].isa_mask & mask) == 0;
           k = ISA_HAZARD_hazard_info[k].next
      );
      ISA_HAZARD_hazard_info[j].next = k;
    }
    if ((ISA_HAZARD_hazard_info[i].isa_mask & mask) == 0) {
      ISA_HAZARD_hazard_index[top] = ISA_HAZARD_hazard_info[i].next;
    }
  }
}
