#include "targ_isa_enums.h"

const ISA_ENUM_CLASS_INFO ISA_ENUM_CLASS_info[] = {
	{ "EC_UNDEFINED",	ECV_UNDEFINED,	ECV_UNDEFINED },
	{ "EC_mwh",	ECV_mwh_sptk,	ECV_mwh },
	{ "EC_ldhint",	ECV_ldhint_nt1,	ECV_ldhint },
	{ "EC_sthint",	ECV_sthint_nta,	ECV_sthint },
	{ "EC_lfhint",	ECV_lfhint_nt1,	ECV_lfhint },
	{ "EC_ph",	ECV_ph_few,	ECV_ph_many },
	{ "EC_bwh",	ECV_bwh_sptk,	ECV_bwh_dpnt },
	{ "EC_dh",	ECV_dh_clr,	ECV_dh },
	{ "EC_ipwh",	ECV_ipwh_sptk,	ECV_ipwh_exit },
	{ "EC_indwh",	ECV_indwh_sptk,	ECV_indwh_dptk },
	{ "EC_ih",	ECV_ih_imp,	ECV_ih },
	{ "EC_aclr",	ECV_aclr_nc,	ECV_aclr_clr },
	{ "EC_sem",	ECV_sem_acq,	ECV_sem_rel },
	{ "EC_ldtype",	ECV_ldtype_s,	ECV_ldtype },
	{ "EC_fldtype",	ECV_fldtype_s,	ECV_fldtype },
	{ "EC_sttype",	ECV_sttype_rel,	ECV_sttype },
	{ "EC_mbtype4",	ECV_mbtype4_brdcst,	ECV_mbtype4_rev },
	{ "EC_sf",	ECV_sf_s0,	ECV_sf_s3 },
};

const ISA_ENUM_CLASS_VALUE_INFO ISA_ENUM_CLASS_VALUE_info[] = {
	{ "UNDEFINED",	-1 },
	{ ".sptk",	0 },
	{ ".dptk",	2 },
	{ "",	1 },
	{ ".nt1",	1 },
	{ ".nta",	3 },
	{ "",	0 },
	{ ".nta",	3 },
	{ "",	0 },
	{ ".nt1",	1 },
	{ ".nt2",	2 },
	{ ".nta",	3 },
	{ "",	0 },
	{ ".few",	0 },
	{ ".many",	1 },
	{ ".sptk",	0 },
	{ ".spnt",	1 },
	{ ".dptk",	2 },
	{ ".dpnt",	3 },
	{ ".clr",	1 },
	{ "",	0 },
	{ ".sptk",	0 },
	{ ".loop",	1 },
	{ ".dptk",	2 },
	{ ".exit",	3 },
	{ ".sptk",	0 },
	{ ".dptk",	2 },
	{ ".imp",	1 },
	{ "",	0 },
	{ ".nc",	0 },
	{ ".clr",	1 },
	{ ".acq",	0 },
	{ ".rel",	1 },
	{ ".s",	1 },
	{ ".a",	2 },
	{ ".sa",	3 },
	{ ".bias",	4 },
	{ ".acq",	5 },
	{ ".c.clr",	8 },
	{ ".c.nc",	9 },
	{ ".c.clr.acq",	10 },
	{ "",	0 },
	{ ".s",	1 },
	{ ".a",	2 },
	{ ".sa",	3 },
	{ ".c.clr",	8 },
	{ ".c.nc",	9 },
	{ "",	0 },
	{ ".rel",	1 },
	{ "",	0 },
	{ "@brdcst",	0 },
	{ "@mix",	8 },
	{ "@shuf",	9 },
	{ "@alt",	10 },
	{ "@rev",	11 },
	{ ".s0",	0 },
	{ ".s1",	1 },
	{ ".s2",	2 },
	{ ".s3",	3 },
};

