#!/bin/bash
#
# Copyright (C) 2006, 2007. QLogic Corporation. All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of version 2 of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# Further, this software is distributed without any warranty that it is
# free of the rightful claim of any third person regarding infringement
# or the like.  Any license provided herein, whether implied or
# otherwise, applies only to this software file.  Patent licenses, if
# any, provided herein do not apply to combinations of this program with
# other software, or any other product whatsoever.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write the Free Software Foundation, Inc., 59
# Temple Place - Suite 330, Boston MA 02111-1307, USA.

find .. -name config.cache | xargs /bin/rm -f
GCCROOT=/opt/sicortex/mips64-gcc
CC='gcc -m32 -DTARG_MIPS' ../configure --prefix=$PWD/../install --with-gnu-ld --with-gnu-as --enable-languages=c,c++ --disable-bootstrap --disable-shared --disable-multilib --disable-libmudflap --enable-threads=posix --disable-checking --with-system-zlib --enable-__cxa_atexit --host=x86_64-redhat-linux --target=mips-elf --with-sysroot=$GCCROOT --with-build-time-tools=$GCCROOT/usr/bin --with-as=$GCCROOT/usr/bin/mips-elf-as --with-ld=$GCCROOT/usr/bin/mips-elf-ld
