PSC_NAME_PREFIX=

PSC_MAJOR_VERSION=3
PSC_MINOR_VERSION=0
PSC_PATCH_LEVEL=

PSC_FULL_VERSION=${PSC_MAJOR_VERSION}.${PSC_MINOR_VERSION}

PSC_GCC_VERSION=3.3.1
PSC_ROOT_PREFIX=
PSC_INSTALL_PREFIX=/usr
PSC_INCLUDE_DIR=
PSC_TARGET=ia64-open64-linux
