//OBJ
//TAG: csmith
typedef short int int16_t; typedef int int32_t; typedef long int int64_t;
typedef unsigned char uint8_t; typedef unsigned short int uint16_t; typedef
unsigned int uint32_t; typedef unsigned long int uint64_t; int32_t g_30[10][2]
= { }; int32_t g_35[2][2][1] = { }; int32_t *g_44 = &g_30[1][1]; int32_t **g_43
= &g_44; int32_t g_87 = (-9L); int64_t g_109 = 1L; const int16_t
func_81(int16_t p_82, uint8_t p_83, int32_t ** p_84, int32_t * p_85, int32_t * const p_86) 
{ int32_t *l_95[5][1]; lbl_184: 
  for (p_83 = 0; p_83 < 5; p_83 += 1)
    { for (p_82 = 0; p_82 < 1; p_82 += 1) { 
        uint64_t l_104 = 18446744073709551615U;
        int32_t **l_105 = 0; 
        int32_t *l_106 = &g_35[0][0][0]; 
        if ((safe_sub_func_uint32_t_u_u(
                                        (safe_mod_func_int16_t_s_s(0x8FB6L,
                                                                   (safe_rshift_func_int8_t_s_s((safe_rshift_func_int8_t_s_s(func_8(p_83,                                                                                  func_8(g_30[1][1], l_104, l_105, l_95[(p_83) % 5][(uint16_t)(p_82) % 1],
                                                                                                                                           l_106), 0, (*g_43), (*g_43)), p_83)), 5)))), func_8(func_8(0xA83E1A65L,
                                                                                                                                                                                                      g_35[0][0][0], &g_44, &g_35[(p_83) % 2][(uint16_t)(p_82) % 2][(uint32_t)(g_87)
                                                                                                                                                                                                                                                                                                                                                                  % 1], (*p_84)), g_30[1][1], &g_44, &g_35[(p_83) % 2][(uint16_t)(p_82) %
                                                                                                                                                                                                                                                                                                                                                                                                                       2][(uint32_t)(g_87) % 1], (*p_84))))) { int32_t * const l_136 = &g_35[(p_83) %
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             2][(uint16_t)(p_82) % 2][(uint32_t)(g_87) % 1]; for (g_87 = 1; (g_87 > (-26));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  g_87 = safe_sub_func_int64_t_s_s(g_87, 1)) { int16_t l_145 = 0xE6B9L; if
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ((*p_86)) { for (g_109 = 3; g_109 < 5; g_109 += 1) { for (l_145 = 0; l_145 < 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    l_145 += 1) { } } } else { for (l_104 = 0; (l_145 == (-19)); l_145 =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      safe_sub_func_int32_t_s_s(l_145, 1)) { int32_t **l_149 = &l_95[(p_83) %
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     5][(uint32_t)((p_82 + 1)) % 1]; (*l_149) = l_136; (*p_86) ^= ((*l_136) >=
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (**l_149)); return p_83; } } for (g_109 = 12; (g_109 != (-28)); g_109 =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       safe_sub_func_int16_t_s_s(g_109, 6)) { } } } } } }
