/* This file is auto-generated by opts.sh.  */

#ifndef OPTIONS_H
#define OPTIONS_H

extern int target_flags;

extern int warn_abi;
extern int warn_address;
extern int warn_aggregate_return;
extern int warn_assign_intercept;
extern int warn_attributes;
extern int warn_bad_function_cast;
extern int warn_cxx_compat;
extern int warn_cast_align;
extern int warn_cast_qual;
extern int warn_char_subscripts;
extern int warn_conversion;
extern int warn_ctor_dtor_privacy;
extern int warn_declaration_after_statement;
extern int warn_deprecated;
extern int warn_deprecated_decl;
extern int warn_disabled_optimization;
extern int warn_div_by_zero;
extern int warn_ecpp;
extern int warnings_are_errors;
extern int flag_fatal_errors;
extern int warn_float_equal;
extern int warn_format_extra_args;
extern int warn_format_nonliteral;
extern int warn_format_security;
extern int warn_format_y2k;
extern int warn_format_zero_length;
extern int mesg_implicit_function_declaration;
extern int warn_implicit_int;
extern int warn_init_self;
extern int warn_inline;
extern int warn_int_to_pointer_cast;
extern int warn_invalid_offsetof;
extern int warn_long_long;
extern int warn_missing_braces;
extern int warn_missing_declarations;
extern int warn_missing_field_initializers;
extern int warn_missing_format_attribute;
extern int warn_missing_noreturn;
extern int warn_missing_prototypes;
extern int warn_nested_externs;
extern int warn_nontemplate_friend;
extern int warn_nonvdtor;
extern int warn_nonnull;
extern int warn_old_style_cast;
extern int warn_old_style_definition;
extern int warn_overflow;
extern int warn_overlength_strings;
extern int warn_overloaded_virtual;
extern int warn_override_init;
extern int warn_packed;
extern int warn_padded;
extern int warn_parentheses;
extern int warn_pmf2ptr;
extern int warn_pointer_arith;
extern int warn_pointer_sign;
extern int warn_pointer_to_int_cast;
extern int warn_pragmas;
extern int warn_protocol;
extern int warn_redundant_decls;
extern int warn_reorder;
extern int warn_return_type;
extern int warn_selector;
extern int warn_sequence_point;
extern int warn_shadow;
extern int warn_sign_compare;
extern int warn_sign_promo;
extern int warn_stack_protect;
extern int warn_strict_prototypes;
extern int warn_strict_selector_match;
extern int warn_switch;
extern int warn_switch_default;
extern int warn_switch_enum;
extern int warn_synth;
extern int warn_system_headers;
extern int warn_traditional;
extern int warn_undeclared_selector;
extern int warn_uninitialized;
extern int warn_notreached;
extern int warn_unsafe_loop_optimizations;
extern int warn_unused_function;
extern int warn_unused_label;
extern int warn_unused_parameter;
extern int warn_unused_value;
extern int warn_unused_variable;
extern int warn_register_var;
extern int warn_write_strings;
extern int flag_pic;
extern int flag_pie;
extern int flag_abi_version;
extern int align_functions;
extern int align_jumps;
extern int align_labels;
extern int align_loops;
extern int flag_argument_noalias;
extern int flag_argument_noalias;
extern int flag_argument_noalias;
extern int flag_argument_noalias;
extern int flag_asynchronous_unwind_tables;
extern int flag_bounds_check;
extern int flag_branch_on_count_reg;
extern int flag_branch_probabilities;
extern int flag_branch_target_load_optimize;
extern int flag_branch_target_load_optimize2;
extern int flag_btr_bb_exclusive;
extern int flag_caller_saves;
extern int flag_no_common;
extern int flag_cprop_registers;
extern int flag_crossjumping;
extern int flag_cse_follow_jumps;
extern int flag_cse_skip_blocks;
extern int flag_cx_limited_range;
extern int open64_cxx_openmp;
extern int flag_data_sections;
extern int flag_defer_pop;
extern int flag_delayed_branch;
extern int flag_delete_null_pointer_checks;
extern int flag_dump_noaddr;
extern int flag_dump_unnumbered;
extern int flag_early_inlining;
extern int flag_eliminate_dwarf2_dups;
extern int flag_debug_only_used_symbols;
extern int flag_eliminate_unused_debug_types;
extern int flag_emit_class_debug_always;
extern int flag_exceptions;
extern int flag_expensive_optimizations;
extern int flag_finite_math_only;
extern int flag_float_store;
extern int flag_force_addr;
extern int flag_force_mem;
extern int flag_friend_injection;
extern int flag_no_function_cse;
extern int flag_function_sections;
extern int flag_gcse;
extern int flag_gcse_after_reload;
extern int flag_gcse_las;
extern int flag_gcse_lm;
extern int flag_gcse_sm;
extern int flag_gnu89_inline;
extern int flag_guess_branch_prob;
extern int flag_honor_shift;
extern int key_i386_host;
extern int flag_no_ident;
extern int flag_if_conversion;
extern int flag_if_conversion2;
extern int flag_inhibit_size_directive;
extern int flag_no_inline;
extern int flag_inline_functions;
extern int flag_inline_functions_called_once;
extern int flag_instrument_function_entry_exit;
extern int flag_ipa_cp;
extern int flag_ipa_pta;
extern int flag_ipa_pure_const;
extern int flag_ipa_reference;
extern int flag_ipa_type_escape;
extern int flag_ivopts;
extern int flag_jump_tables;
extern int flag_keep_inline_functions;
extern int flag_keep_static_consts;
extern int flag_leading_underscore;
extern int flag_errno_math;
extern int mem_report;
extern int flag_merge_constants;
extern int flag_merge_constants;
extern int flag_modulo_sched;
extern int flag_move_loop_invariants;
extern int flag_mudflap;
extern int flag_mudflap_ignore_reads;
extern int flag_mudflap;
extern int flag_non_call_exceptions;
extern int flag_objc_call_cxx_cdtors;
extern int flag_objc_direct_dispatch;
extern int flag_objc_exceptions;
extern int flag_objc_gc;
extern int flag_objc_sjlj_exceptions;
extern int flag_omit_frame_pointer;
extern int flag_openmp;
extern int flag_regmove;
extern int flag_optimize_sibling_calls;
extern int flag_pack_struct;
extern int flag_pcc_struct_return;
extern int flag_peel_loops;
extern int flag_no_peephole;
extern int flag_peephole2;
extern int flag_pic;
extern int flag_pie;
extern int flag_prefetch_loop_arrays;
extern int profile_flag;
extern int profile_arc_flag;
extern int flag_profile_values;
extern int flag_pcc_struct_return;
extern int flag_regmove;
extern int flag_rename_registers;
extern int flag_reorder_blocks;
extern int flag_reorder_blocks_and_partition;
extern int flag_reorder_functions;
extern int flag_rerun_cse_after_loop;
extern int flag_resched_modulo_sched;
extern int flag_rounding_math;
extern int flag_rtl_seqabstr;
extern int flag_schedule_interblock;
extern int flag_schedule_speculative;
extern int flag_schedule_speculative_load;
extern int flag_schedule_speculative_load_dangerous;
extern int flag_sched_stalled_insns;
extern int flag_sched_stalled_insns_dep;
extern int flag_sched2_use_superblocks;
extern int flag_sched2_use_traces;
extern int flag_schedule_insns;
extern int flag_schedule_insns_after_reload;
extern int flag_section_anchors;
extern int flag_see;
extern int flag_show_column;
extern int flag_signaling_nans;
extern int flag_single_precision_constant;
extern int flag_split_ivs_in_unroller;
extern int flag_stack_check;
extern int flag_stack_protect;
extern int flag_stack_protect;
extern int flag_strict_aliasing;
extern int flag_strict_overflow;
extern int flag_syntax_only;
extern int flag_test_coverage;
extern int flag_thread_jumps;
extern int time_report;
extern int flag_toplevel_reorder;
extern int flag_tracer;
extern int flag_trapping_math;
extern int flag_trapv;
extern int flag_tree_ccp;
extern int flag_tree_ch;
extern int flag_tree_combine_temps;
extern int flag_tree_copy_prop;
extern int flag_tree_copyrename;
extern int flag_tree_dce;
extern int flag_tree_dom;
extern int flag_tree_dse;
extern int flag_tree_fre;
extern int flag_tree_loop_im;
extern int flag_tree_loop_ivcanon;
extern int flag_tree_loop_linear;
extern int flag_tree_loop_optimize;
extern int flag_tree_live_range_split;
extern int flag_tree_pre;
extern int flag_tree_salias;
extern int flag_tree_sink;
extern int flag_tree_sra;
extern int flag_tree_store_ccp;
extern int flag_tree_store_copy_prop;
extern int flag_tree_ter;
extern int flag_tree_vect_loop_version;
extern int flag_tree_vectorize;
extern int flag_tree_vrp;
extern int flag_unit_at_a_time;
extern int flag_unroll_all_loops;
extern int flag_unroll_loops;
extern int flag_unsafe_loop_optimizations;
extern int flag_unsafe_math_optimizations;
extern int flag_unswitch_loops;
extern int flag_unwind_tables;
extern int flag_var_tracking;
extern int flag_variable_expansion_in_unroller;
extern int flag_verbose_asm;
extern int flag_value_profile_transformations;
extern int flag_web;
extern int flag_whole_program;
extern int flag_wrapv;
extern int flag_zero_initialized_in_bss;
extern int ix86_isa_flags;
extern const char *ix86_align_funcs_string;
extern const char *ix86_align_jumps_string;
extern const char *ix86_align_loops_string;
extern const char *ix86_arch_string;
extern const char *ix86_asm_string;
extern int ix86_isa_flags;
extern const char *ix86_branch_cost_string;
extern const char *ix86_cmodel_string;
extern int TARGET_DEBUG_ADDR;
extern int TARGET_DEBUG_ARG;
extern int ix86_isa_flags;
extern const char *ix86_fpmath_string;
extern int linux_uclibc;
extern const char *ix86_section_threshold_string;
extern int ix86_isa_flags;
extern int ix86_isa_flags;
extern int ix86_isa_flags;
extern int ix86_isa_flags;
extern int ix86_isa_flags;
extern const char *ix86_preferred_stack_boundary_string;
extern const char *ix86_regparm_string;
extern int ix86_isa_flags;
extern int ix86_isa_flags;
extern int ix86_isa_flags;
extern int ix86_isa_flags;
extern int ix86_force_align_arg_pointer;
extern const char *ix86_tls_dialect_string;
extern const char *ix86_tune_string;
extern int linux_uclibc;
extern int ix86_isa_flags;
extern int ix86_isa_flags;
extern int profile_flag;
extern int pedantic;
extern int quiet_flag;
extern int version_flag;
extern int inhibit_warnings;

#define MASK_128BIT_LONG_DOUBLE (1 << 0)
#define MASK_3DNOW (1 << 1)
#define MASK_64BIT (1 << 2)
#define MASK_80387 (1 << 3)
#define MASK_ACCUMULATE_OUTGOING_ARGS (1 << 4)
#define OPTION_MASK_ISA_AES (1 << 0)
#define MASK_ALIGN_DOUBLE (1 << 5)
#define OPTION_MASK_ISA_AVX (1 << 1)
#define OPTION_MASK_ISA_FMA4 (1 << 2)
#define MASK_FLOAT_RETURNS (1 << 6)
#define MASK_IEEE_FP (1 << 7)
#define MASK_INLINE_ALL_STRINGOPS (1 << 8)
#define MASK_MMX (1 << 9)
#define MASK_MS_BITFIELD_LAYOUT (1 << 10)
#define MASK_NO_ALIGN_STRINGOPS (1 << 11)
#define MASK_NO_FANCY_MATH_387 (1 << 12)
#define MASK_NO_PUSH_ARGS (1 << 13)
#define MASK_NO_RED_ZONE (1 << 14)
#define MASK_OMIT_LEAF_FRAME_POINTER (1 << 15)
#define OPTION_MASK_ISA_PCLMUL (1 << 3)
#define MASK_RTD (1 << 16)
#define MASK_SSE (1 << 17)
#define MASK_SSE2 (1 << 18)
#define MASK_SSE3 (1 << 19)
#define OPTION_MASK_ISA_SSE4_1 (1 << 4)
#define OPTION_MASK_ISA_SSE4_2 (1 << 5)
#define MASK_SSE4A (1 << 20)
#define MASK_SSEREGPARM (1 << 21)
#define OPTION_MASK_ISA_SSSE3 (1 << 6)
#define MASK_STACK_PROBE (1 << 22)
#define MASK_SVR3_SHLIB (1 << 23)
#define MASK_TLS_DIRECT_SEG_REFS (1 << 24)
#define OPTION_MASK_UCLIBC (1 << 0)
#define OPTION_MASK_ISA_XFC (1 << 7)
#define OPTION_MASK_ISA_XOP (1 << 8)
#define MASK_3DNOW_A (1 << 25)

#define TARGET_128BIT_LONG_DOUBLE ((target_flags & MASK_128BIT_LONG_DOUBLE) != 0)
#define TARGET_3DNOW ((target_flags & MASK_3DNOW) != 0)
#define TARGET_64BIT ((target_flags & MASK_64BIT) != 0)
#define TARGET_80387 ((target_flags & MASK_80387) != 0)
#define TARGET_ACCUMULATE_OUTGOING_ARGS ((target_flags & MASK_ACCUMULATE_OUTGOING_ARGS) != 0)
#define OPTION_ISA_AES ((ix86_isa_flags & OPTION_MASK_ISA_AES) != 0)
#define TARGET_ALIGN_DOUBLE ((target_flags & MASK_ALIGN_DOUBLE) != 0)
#define OPTION_ISA_AVX ((ix86_isa_flags & OPTION_MASK_ISA_AVX) != 0)
#define OPTION_ISA_FMA4 ((ix86_isa_flags & OPTION_MASK_ISA_FMA4) != 0)
#define TARGET_FLOAT_RETURNS ((target_flags & MASK_FLOAT_RETURNS) != 0)
#define TARGET_IEEE_FP ((target_flags & MASK_IEEE_FP) != 0)
#define TARGET_INLINE_ALL_STRINGOPS ((target_flags & MASK_INLINE_ALL_STRINGOPS) != 0)
#define TARGET_MMX ((target_flags & MASK_MMX) != 0)
#define TARGET_MS_BITFIELD_LAYOUT ((target_flags & MASK_MS_BITFIELD_LAYOUT) != 0)
#define TARGET_NO_ALIGN_STRINGOPS ((target_flags & MASK_NO_ALIGN_STRINGOPS) != 0)
#define TARGET_NO_FANCY_MATH_387 ((target_flags & MASK_NO_FANCY_MATH_387) != 0)
#define TARGET_NO_PUSH_ARGS ((target_flags & MASK_NO_PUSH_ARGS) != 0)
#define TARGET_NO_RED_ZONE ((target_flags & MASK_NO_RED_ZONE) != 0)
#define TARGET_OMIT_LEAF_FRAME_POINTER ((target_flags & MASK_OMIT_LEAF_FRAME_POINTER) != 0)
#define OPTION_ISA_PCLMUL ((ix86_isa_flags & OPTION_MASK_ISA_PCLMUL) != 0)
#define TARGET_RTD ((target_flags & MASK_RTD) != 0)
#define TARGET_SSE ((target_flags & MASK_SSE) != 0)
#define TARGET_SSE2 ((target_flags & MASK_SSE2) != 0)
#define TARGET_SSE3 ((target_flags & MASK_SSE3) != 0)
#define OPTION_ISA_SSE4_1 ((ix86_isa_flags & OPTION_MASK_ISA_SSE4_1) != 0)
#define OPTION_ISA_SSE4_2 ((ix86_isa_flags & OPTION_MASK_ISA_SSE4_2) != 0)
#define TARGET_SSE4A ((target_flags & MASK_SSE4A) != 0)
#define TARGET_SSEREGPARM ((target_flags & MASK_SSEREGPARM) != 0)
#define OPTION_ISA_SSSE3 ((ix86_isa_flags & OPTION_MASK_ISA_SSSE3) != 0)
#define TARGET_STACK_PROBE ((target_flags & MASK_STACK_PROBE) != 0)
#define TARGET_SVR3_SHLIB ((target_flags & MASK_SVR3_SHLIB) != 0)
#define TARGET_TLS_DIRECT_SEG_REFS ((target_flags & MASK_TLS_DIRECT_SEG_REFS) != 0)
#define OPTION_UCLIBC ((linux_uclibc & OPTION_MASK_UCLIBC) != 0)
#define OPTION_ISA_XFC ((ix86_isa_flags & OPTION_MASK_ISA_XFC) != 0)
#define OPTION_ISA_XOP ((ix86_isa_flags & OPTION_MASK_ISA_XOP) != 0)
#define TARGET_3DNOW_A ((target_flags & MASK_3DNOW_A) != 0)

#define TARGET_ALIGN_STRINGOPS ((target_flags & MASK_NO_ALIGN_STRINGOPS) == 0)
#define TARGET_USE_FANCY_MATH_387 ((target_flags & MASK_NO_FANCY_MATH_387) == 0)
#define OPTION_GLIBC ((linux_uclibc & OPTION_MASK_UCLIBC) == 0)
#define TARGET_PUSH_ARGS ((target_flags & MASK_NO_PUSH_ARGS) == 0)
#define TARGET_RED_ZONE ((target_flags & MASK_NO_RED_ZONE) == 0)

#define CL_C          (1 << 0)
#define CL_CXX        (1 << 1)
#define CL_ObjC       (1 << 2)
#define CL_ObjCXX     (1 << 3)

enum opt_code
{
  OPT__help,                                 /* --help */
  OPT__output_pch_,                          /* --output-pch= */
  OPT__param,                                /* --param */
  OPT__target_help,                          /* --target-help */
  OPT__version,                              /* --version */
  OPT_A,                                     /* -A */
  OPT_C,                                     /* -C */
  OPT_CC,                                    /* -CC */
  OPT_D,                                     /* -D */
  OPT_E,                                     /* -E */
  OPT_F,                                     /* -F */
  OPT_G,                                     /* -G */
  OPT_H,                                     /* -H */
  OPT_I,                                     /* -I */
  OPT_M,                                     /* -M */
  OPT_MD,                                    /* -MD */
  OPT_MF,                                    /* -MF */
  OPT_MG,                                    /* -MG */
  OPT_MM,                                    /* -MM */
  OPT_MMD,                                   /* -MMD */
  OPT_MP,                                    /* -MP */
  OPT_MQ,                                    /* -MQ */
  OPT_MT,                                    /* -MT */
  OPT_O,                                     /* -O */
  OPT_Os,                                    /* -Os */
  OPT_P,                                     /* -P */
  OPT_U,                                     /* -U */
  OPT_W,                                     /* -W */
  OPT_Wabi,                                  /* -Wabi */
  OPT_Waddress,                              /* -Waddress */
  OPT_Waggregate_return,                     /* -Waggregate-return */
  OPT_Wall,                                  /* -Wall */
  OPT_Wassign_intercept,                     /* -Wassign-intercept */
  OPT_Wattributes,                           /* -Wattributes */
  OPT_Wbad_function_cast,                    /* -Wbad-function-cast */
  OPT_Wc___compat,                           /* -Wc++-compat */
  OPT_Wcast_align,                           /* -Wcast-align */
  OPT_Wcast_qual,                            /* -Wcast-qual */
  OPT_Wchar_subscripts,                      /* -Wchar-subscripts */
  OPT_Wcomment,                              /* -Wcomment */
  OPT_Wcomments,                             /* -Wcomments */
  OPT_Wconversion,                           /* -Wconversion */
  OPT_Wctor_dtor_privacy,                    /* -Wctor-dtor-privacy */
  OPT_Wdeclaration_after_statement,          /* -Wdeclaration-after-statement */
  OPT_Wdeprecated,                           /* -Wdeprecated */
  OPT_Wdeprecated_declarations,              /* -Wdeprecated-declarations */
  OPT_Wdisabled_optimization,                /* -Wdisabled-optimization */
  OPT_Wdiv_by_zero,                          /* -Wdiv-by-zero */
  OPT_Weffc__,                               /* -Weffc++ */
  OPT_Wendif_labels,                         /* -Wendif-labels */
  OPT_Werror,                                /* -Werror */
  OPT_Werror_implicit_function_declaration,  /* -Werror-implicit-function-declaration */
  OPT_Werror_,                               /* -Werror= */
  OPT_Wextra,                                /* -Wextra */
  OPT_Wfatal_errors,                         /* -Wfatal-errors */
  OPT_Wfloat_equal,                          /* -Wfloat-equal */
  OPT_Wformat,                               /* -Wformat */
  OPT_Wformat_extra_args,                    /* -Wformat-extra-args */
  OPT_Wformat_nonliteral,                    /* -Wformat-nonliteral */
  OPT_Wformat_security,                      /* -Wformat-security */
  OPT_Wformat_y2k,                           /* -Wformat-y2k */
  OPT_Wformat_zero_length,                   /* -Wformat-zero-length */
  OPT_Wformat_,                              /* -Wformat= */
  OPT_Wimplicit,                             /* -Wimplicit */
  OPT_Wimplicit_function_declaration,        /* -Wimplicit-function-declaration */
  OPT_Wimplicit_int,                         /* -Wimplicit-int */
  OPT_Wimport,                               /* -Wimport */
  OPT_Winit_self,                            /* -Winit-self */
  OPT_Winline,                               /* -Winline */
  OPT_Wint_to_pointer_cast,                  /* -Wint-to-pointer-cast */
  OPT_Winvalid_offsetof,                     /* -Winvalid-offsetof */
  OPT_Winvalid_pch,                          /* -Winvalid-pch */
  OPT_Wlarger_than_,                         /* -Wlarger-than- */
  OPT_Wlong_long,                            /* -Wlong-long */
  OPT_Wmain,                                 /* -Wmain */
  OPT_Wmissing_braces,                       /* -Wmissing-braces */
  OPT_Wmissing_declarations,                 /* -Wmissing-declarations */
  OPT_Wmissing_field_initializers,           /* -Wmissing-field-initializers */
  OPT_Wmissing_format_attribute,             /* -Wmissing-format-attribute */
  OPT_Wmissing_include_dirs,                 /* -Wmissing-include-dirs */
  OPT_Wmissing_noreturn,                     /* -Wmissing-noreturn */
  OPT_Wmissing_prototypes,                   /* -Wmissing-prototypes */
  OPT_Wmultichar,                            /* -Wmultichar */
  OPT_Wnested_externs,                       /* -Wnested-externs */
  OPT_Wnon_template_friend,                  /* -Wnon-template-friend */
  OPT_Wnon_virtual_dtor,                     /* -Wnon-virtual-dtor */
  OPT_Wnonnull,                              /* -Wnonnull */
  OPT_Wnormalized_,                          /* -Wnormalized= */
  OPT_Wold_style_cast,                       /* -Wold-style-cast */
  OPT_Wold_style_definition,                 /* -Wold-style-definition */
  OPT_Woverflow,                             /* -Woverflow */
  OPT_Woverlength_strings,                   /* -Woverlength-strings */
  OPT_Woverloaded_virtual,                   /* -Woverloaded-virtual */
  OPT_Woverride_init,                        /* -Woverride-init */
  OPT_Wpacked,                               /* -Wpacked */
  OPT_Wpadded,                               /* -Wpadded */
  OPT_Wparentheses,                          /* -Wparentheses */
  OPT_Wpmf_conversions,                      /* -Wpmf-conversions */
  OPT_Wpointer_arith,                        /* -Wpointer-arith */
  OPT_Wpointer_sign,                         /* -Wpointer-sign */
  OPT_Wpointer_to_int_cast,                  /* -Wpointer-to-int-cast */
  OPT_Wpragmas,                              /* -Wpragmas */
  OPT_Wprotocol,                             /* -Wprotocol */
  OPT_Wredundant_decls,                      /* -Wredundant-decls */
  OPT_Wreorder,                              /* -Wreorder */
  OPT_Wreturn_type,                          /* -Wreturn-type */
  OPT_Wselector,                             /* -Wselector */
  OPT_Wsequence_point,                       /* -Wsequence-point */
  OPT_Wshadow,                               /* -Wshadow */
  OPT_Wsign_compare,                         /* -Wsign-compare */
  OPT_Wsign_promo,                           /* -Wsign-promo */
  OPT_Wstack_protector,                      /* -Wstack-protector */
  OPT_Wstrict_aliasing,                      /* -Wstrict-aliasing */
  OPT_Wstrict_aliasing_,                     /* -Wstrict-aliasing= */
  OPT_Wstrict_null_sentinel,                 /* -Wstrict-null-sentinel */
  OPT_Wstrict_overflow,                      /* -Wstrict-overflow */
  OPT_Wstrict_overflow_,                     /* -Wstrict-overflow= */
  OPT_Wstrict_prototypes,                    /* -Wstrict-prototypes */
  OPT_Wstrict_selector_match,                /* -Wstrict-selector-match */
  OPT_Wswitch,                               /* -Wswitch */
  OPT_Wswitch_default,                       /* -Wswitch-default */
  OPT_Wswitch_enum,                          /* -Wswitch-enum */
  OPT_Wsynth,                                /* -Wsynth */
  OPT_Wsystem_headers,                       /* -Wsystem-headers */
  OPT_Wtraditional,                          /* -Wtraditional */
  OPT_Wtrigraphs,                            /* -Wtrigraphs */
  OPT_Wundeclared_selector,                  /* -Wundeclared-selector */
  OPT_Wundef,                                /* -Wundef */
  OPT_Wuninitialized,                        /* -Wuninitialized */
  OPT_Wunknown_pragmas,                      /* -Wunknown-pragmas */
  OPT_Wunreachable_code,                     /* -Wunreachable-code */
  OPT_Wunsafe_loop_optimizations,            /* -Wunsafe-loop-optimizations */
  OPT_Wunused,                               /* -Wunused */
  OPT_Wunused_function,                      /* -Wunused-function */
  OPT_Wunused_label,                         /* -Wunused-label */
  OPT_Wunused_macros,                        /* -Wunused-macros */
  OPT_Wunused_parameter,                     /* -Wunused-parameter */
  OPT_Wunused_value,                         /* -Wunused-value */
  OPT_Wunused_variable,                      /* -Wunused-variable */
  OPT_Wvariadic_macros,                      /* -Wvariadic-macros */
  OPT_Wvolatile_register_var,                /* -Wvolatile-register-var */
  OPT_Wwrite_strings,                        /* -Wwrite-strings */
  OPT_ansi,                                  /* -ansi */
  OPT_aux_info,                              /* -aux-info */
  OPT_aux_info_,                             /* -aux-info= */
  OPT_auxbase,                               /* -auxbase */
  OPT_auxbase_strip,                         /* -auxbase-strip */
  OPT_d,                                     /* -d */
  OPT_dumpbase,                              /* -dumpbase */
  OPT_fPIC,                                  /* -fPIC */
  OPT_fPIE,                                  /* -fPIE */
  OPT_fabi_version_,                         /* -fabi-version= */
  OPT_faccess_control,                       /* -faccess-control */
  OPT_falign_functions,                      /* -falign-functions */
  OPT_falign_functions_,                     /* -falign-functions= */
  OPT_falign_jumps,                          /* -falign-jumps */
  OPT_falign_jumps_,                         /* -falign-jumps= */
  OPT_falign_labels,                         /* -falign-labels */
  OPT_falign_labels_,                        /* -falign-labels= */
  OPT_falign_loops,                          /* -falign-loops */
  OPT_falign_loops_,                         /* -falign-loops= */
  OPT_fall_virtual,                          /* -fall-virtual */
  OPT_falt_external_templates,               /* -falt-external-templates */
  OPT_fargument_alias,                       /* -fargument-alias */
  OPT_fargument_noalias,                     /* -fargument-noalias */
  OPT_fargument_noalias_anything,            /* -fargument-noalias-anything */
  OPT_fargument_noalias_global,              /* -fargument-noalias-global */
  OPT_fasm,                                  /* -fasm */
  OPT_fasynchronous_unwind_tables,           /* -fasynchronous-unwind-tables */
  OPT_fbounds_check,                         /* -fbounds-check */
  OPT_fbranch_count_reg,                     /* -fbranch-count-reg */
  OPT_fbranch_probabilities,                 /* -fbranch-probabilities */
  OPT_fbranch_target_load_optimize,          /* -fbranch-target-load-optimize */
  OPT_fbranch_target_load_optimize2,         /* -fbranch-target-load-optimize2 */
  OPT_fbtr_bb_exclusive,                     /* -fbtr-bb-exclusive */
  OPT_fbuiltin,                              /* -fbuiltin */
  OPT_fbuiltin_,                             /* -fbuiltin- */
  OPT_fc_omit_external,                      /* -fc-omit-external */
  OPT_fcall_saved_,                          /* -fcall-saved- */
  OPT_fcall_used_,                           /* -fcall-used- */
  OPT_fcaller_saves,                         /* -fcaller-saves */
  OPT_fcheck_new,                            /* -fcheck-new */
  OPT_fcommon,                               /* -fcommon */
  OPT_fcond_mismatch,                        /* -fcond-mismatch */
  OPT_fconserve_space,                       /* -fconserve-space */
  OPT_fconstant_string_class_,               /* -fconstant-string-class= */
  OPT_fcprop_registers,                      /* -fcprop-registers */
  OPT_fcrossjumping,                         /* -fcrossjumping */
  OPT_fcse_follow_jumps,                     /* -fcse-follow-jumps */
  OPT_fcse_skip_blocks,                      /* -fcse-skip-blocks */
  OPT_fcx_limited_range,                     /* -fcx-limited-range */
  OPT_fcxx_openmp,                           /* -fcxx-openmp */
  OPT_fdata_sections,                        /* -fdata-sections */
  OPT_fdefault_inline,                       /* -fdefault-inline */
  OPT_fdefer_pop,                            /* -fdefer-pop */
  OPT_fdelayed_branch,                       /* -fdelayed-branch */
  OPT_fdelete_null_pointer_checks,           /* -fdelete-null-pointer-checks */
  OPT_fdiagnostics_show_location_,           /* -fdiagnostics-show-location= */
  OPT_fdiagnostics_show_option,              /* -fdiagnostics-show-option */
  OPT_fdollars_in_identifiers,               /* -fdollars-in-identifiers */
  OPT_fdump_,                                /* -fdump- */
  OPT_fdump_noaddr,                          /* -fdump-noaddr */
  OPT_fdump_unnumbered,                      /* -fdump-unnumbered */
  OPT_fearly_inlining,                       /* -fearly-inlining */
  OPT_felide_constructors,                   /* -felide-constructors */
  OPT_feliminate_dwarf2_dups,                /* -feliminate-dwarf2-dups */
  OPT_feliminate_unused_debug_symbols,       /* -feliminate-unused-debug-symbols */
  OPT_feliminate_unused_debug_types,         /* -feliminate-unused-debug-types */
  OPT_femit_class_debug_always,              /* -femit-class-debug-always */
  OPT_fenforce_eh_specs,                     /* -fenforce-eh-specs */
  OPT_fenum_int_equiv,                       /* -fenum-int-equiv */
  OPT_fexceptions,                           /* -fexceptions */
  OPT_fexec_charset_,                        /* -fexec-charset= */
  OPT_fexpensive_optimizations,              /* -fexpensive-optimizations */
  OPT_fextended_identifiers,                 /* -fextended-identifiers */
  OPT_fexternal_templates,                   /* -fexternal-templates */
  OPT_ffast_math,                            /* -ffast-math */
  OPT_ffinite_math_only,                     /* -ffinite-math-only */
  OPT_ffixed_,                               /* -ffixed- */
  OPT_ffloat_store,                          /* -ffloat-store */
  OPT_ffor_scope,                            /* -ffor-scope */
  OPT_fforce_addr,                           /* -fforce-addr */
  OPT_fforce_mem,                            /* -fforce-mem */
  OPT_ffreestanding,                         /* -ffreestanding */
  OPT_ffriend_injection,                     /* -ffriend-injection */
  OPT_ffunction_cse,                         /* -ffunction-cse */
  OPT_ffunction_sections,                    /* -ffunction-sections */
  OPT_fgcse,                                 /* -fgcse */
  OPT_fgcse_after_reload,                    /* -fgcse-after-reload */
  OPT_fgcse_las,                             /* -fgcse-las */
  OPT_fgcse_lm,                              /* -fgcse-lm */
  OPT_fgcse_sm,                              /* -fgcse-sm */
  OPT_fgnu_keywords,                         /* -fgnu-keywords */
  OPT_fgnu_runtime,                          /* -fgnu-runtime */
  OPT_fgnu89_inline,                         /* -fgnu89-inline */
  OPT_fguess_branch_probability,             /* -fguess-branch-probability */
  OPT_fguiding_decls,                        /* -fguiding-decls */
  OPT_fhandle_exceptions,                    /* -fhandle-exceptions */
  OPT_fhonor_shift,                          /* -fhonor-shift */
  OPT_fhonor_std,                            /* -fhonor-std */
  OPT_fhosted,                               /* -fhosted */
  OPT_fhuge_objects,                         /* -fhuge-objects */
  OPT_fi386_host,                            /* -fi386-host */
  OPT_fident,                                /* -fident */
  OPT_fif_conversion,                        /* -fif-conversion */
  OPT_fif_conversion2,                       /* -fif-conversion2 */
  OPT_fimplement_inlines,                    /* -fimplement-inlines */
  OPT_fimplicit_inline_templates,            /* -fimplicit-inline-templates */
  OPT_fimplicit_templates,                   /* -fimplicit-templates */
  OPT_finhibit_size_directive,               /* -finhibit-size-directive */
  OPT_finline,                               /* -finline */
  OPT_finline_functions,                     /* -finline-functions */
  OPT_finline_functions_called_once,         /* -finline-functions-called-once */
  OPT_finline_limit_,                        /* -finline-limit- */
  OPT_finline_limit_eq,                        /* -finline-limit= */
  OPT_finput_charset_,                       /* -finput-charset= */
  OPT_finstrument_functions,                 /* -finstrument-functions */
  OPT_fipa_cp,                               /* -fipa-cp */
  OPT_fipa_pta,                              /* -fipa-pta */
  OPT_fipa_pure_const,                       /* -fipa-pure-const */
  OPT_fipa_reference,                        /* -fipa-reference */
  OPT_fipa_type_escape,                      /* -fipa-type-escape */
  OPT_fivopts,                               /* -fivopts */
  OPT_fjump_tables,                          /* -fjump-tables */
  OPT_fkeep_inline_functions,                /* -fkeep-inline-functions */
  OPT_fkeep_static_consts,                   /* -fkeep-static-consts */
  OPT_flabels_ok,                            /* -flabels-ok */
  OPT_fleading_underscore,                   /* -fleading-underscore */
  OPT_floop_optimize,                        /* -floop-optimize */
  OPT_fmath_errno,                           /* -fmath-errno */
  OPT_fmem_report,                           /* -fmem-report */
  OPT_fmerge_all_constants,                  /* -fmerge-all-constants */
  OPT_fmerge_constants,                      /* -fmerge-constants */
  OPT_fmessage_length_,                      /* -fmessage-length= */
  OPT_fmodulo_sched,                         /* -fmodulo-sched */
  OPT_fmove_loop_invariants,                 /* -fmove-loop-invariants */
  OPT_fms_extensions,                        /* -fms-extensions */
  OPT_fmudflap,                              /* -fmudflap */
  OPT_fmudflapir,                            /* -fmudflapir */
  OPT_fmudflapth,                            /* -fmudflapth */
  OPT_fname_mangling_version_,               /* -fname-mangling-version- */
  OPT_fnew_abi,                              /* -fnew-abi */
  OPT_fnext_runtime,                         /* -fnext-runtime */
  OPT_fnil_receivers,                        /* -fnil-receivers */
  OPT_fnon_call_exceptions,                  /* -fnon-call-exceptions */
  OPT_fnonansi_builtins,                     /* -fnonansi-builtins */
  OPT_fnonnull_objects,                      /* -fnonnull-objects */
  OPT_fobjc_call_cxx_cdtors,                 /* -fobjc-call-cxx-cdtors */
  OPT_fobjc_direct_dispatch,                 /* -fobjc-direct-dispatch */
  OPT_fobjc_exceptions,                      /* -fobjc-exceptions */
  OPT_fobjc_gc,                              /* -fobjc-gc */
  OPT_fobjc_sjlj_exceptions,                 /* -fobjc-sjlj-exceptions */
  OPT_fomit_frame_pointer,                   /* -fomit-frame-pointer */
  OPT_fopenmp,                               /* -fopenmp */
  OPT_foperator_names,                       /* -foperator-names */
  OPT_foptimize_register_move,               /* -foptimize-register-move */
  OPT_foptimize_sibling_calls,               /* -foptimize-sibling-calls */
  OPT_foptional_diags,                       /* -foptional-diags */
  OPT_fpack_struct,                          /* -fpack-struct */
  OPT_fpack_struct_,                         /* -fpack-struct= */
  OPT_fpcc_struct_return,                    /* -fpcc-struct-return */
  OPT_fpch_deps,                             /* -fpch-deps */
  OPT_fpch_preprocess,                       /* -fpch-preprocess */
  OPT_fpeel_loops,                           /* -fpeel-loops */
  OPT_fpeephole,                             /* -fpeephole */
  OPT_fpeephole2,                            /* -fpeephole2 */
  OPT_fpermissive,                           /* -fpermissive */
  OPT_fpic,                                  /* -fpic */
  OPT_fpie,                                  /* -fpie */
  OPT_fprefetch_loop_arrays,                 /* -fprefetch-loop-arrays */
  OPT_fpreprocessed,                         /* -fpreprocessed */
  OPT_fprofile,                              /* -fprofile */
  OPT_fprofile_arcs,                         /* -fprofile-arcs */
  OPT_fprofile_generate,                     /* -fprofile-generate */
  OPT_fprofile_use,                          /* -fprofile-use */
  OPT_fprofile_values,                       /* -fprofile-values */
  OPT_frandom_seed,                          /* -frandom-seed */
  OPT_frandom_seed_,                         /* -frandom-seed= */
  OPT_freg_struct_return,                    /* -freg-struct-return */
  OPT_fregmove,                              /* -fregmove */
  OPT_frename_registers,                     /* -frename-registers */
  OPT_freorder_blocks,                       /* -freorder-blocks */
  OPT_freorder_blocks_and_partition,         /* -freorder-blocks-and-partition */
  OPT_freorder_functions,                    /* -freorder-functions */
  OPT_freplace_objc_classes,                 /* -freplace-objc-classes */
  OPT_frepo,                                 /* -frepo */
  OPT_frerun_cse_after_loop,                 /* -frerun-cse-after-loop */
  OPT_frerun_loop_opt,                       /* -frerun-loop-opt */
  OPT_freschedule_modulo_scheduled_loops,    /* -freschedule-modulo-scheduled-loops */
  OPT_frounding_math,                        /* -frounding-math */
  OPT_frtl_abstract_sequences,               /* -frtl-abstract-sequences */
  OPT_frtti,                                 /* -frtti */
  OPT_fsched_interblock,                     /* -fsched-interblock */
  OPT_fsched_spec,                           /* -fsched-spec */
  OPT_fsched_spec_load,                      /* -fsched-spec-load */
  OPT_fsched_spec_load_dangerous,            /* -fsched-spec-load-dangerous */
  OPT_fsched_stalled_insns,                  /* -fsched-stalled-insns */
  OPT_fsched_stalled_insns_dep,              /* -fsched-stalled-insns-dep */
  OPT_fsched_stalled_insns_dep_,             /* -fsched-stalled-insns-dep= */
  OPT_fsched_stalled_insns_,                 /* -fsched-stalled-insns= */
  OPT_fsched_verbose_,                       /* -fsched-verbose= */
  OPT_fsched2_use_superblocks,               /* -fsched2-use-superblocks */
  OPT_fsched2_use_traces,                    /* -fsched2-use-traces */
  OPT_fschedule_insns,                       /* -fschedule-insns */
  OPT_fschedule_insns2,                      /* -fschedule-insns2 */
  OPT_fsection_anchors,                      /* -fsection-anchors */
  OPT_fsee,                                  /* -fsee */
  OPT_fshort_double,                         /* -fshort-double */
  OPT_fshort_enums,                          /* -fshort-enums */
  OPT_fshort_wchar,                          /* -fshort-wchar */
  OPT_fshow_column,                          /* -fshow-column */
  OPT_fsignaling_nans,                       /* -fsignaling-nans */
  OPT_fsigned_bitfields,                     /* -fsigned-bitfields */
  OPT_fsigned_char,                          /* -fsigned-char */
  OPT_fsingle_precision_constant,            /* -fsingle-precision-constant */
  OPT_fsplit_ivs_in_unroller,                /* -fsplit-ivs-in-unroller */
  OPT_fsquangle,                             /* -fsquangle */
  OPT_fstack_check,                          /* -fstack-check */
  OPT_fstack_limit,                          /* -fstack-limit */
  OPT_fstack_limit_register_,                /* -fstack-limit-register= */
  OPT_fstack_limit_symbol_,                  /* -fstack-limit-symbol= */
  OPT_fstack_protector,                      /* -fstack-protector */
  OPT_fstack_protector_all,                  /* -fstack-protector-all */
  OPT_fstats,                                /* -fstats */
  OPT_fstrength_reduce,                      /* -fstrength-reduce */
  OPT_fstrict_aliasing,                      /* -fstrict-aliasing */
  OPT_fstrict_overflow,                      /* -fstrict-overflow */
  OPT_fstrict_prototype,                     /* -fstrict-prototype */
  OPT_fsyntax_only,                          /* -fsyntax-only */
  OPT_ftabstop_,                             /* -ftabstop= */
  OPT_ftemplate_depth_,                      /* -ftemplate-depth- */
  OPT_ftest_coverage,                        /* -ftest-coverage */
  OPT_fthis_is_variable,                     /* -fthis-is-variable */
  OPT_fthread_jumps,                         /* -fthread-jumps */
  OPT_fthreadsafe_statics,                   /* -fthreadsafe-statics */
  OPT_ftime_report,                          /* -ftime-report */
  OPT_ftls_model_,                           /* -ftls-model= */
  OPT_ftoplevel_reorder,                     /* -ftoplevel-reorder */
  OPT_ftracer,                               /* -ftracer */
  OPT_ftrapping_math,                        /* -ftrapping-math */
  OPT_ftrapv,                                /* -ftrapv */
  OPT_ftree_ccp,                             /* -ftree-ccp */
  OPT_ftree_ch,                              /* -ftree-ch */
  OPT_ftree_combine_temps,                   /* -ftree-combine-temps */
  OPT_ftree_copy_prop,                       /* -ftree-copy-prop */
  OPT_ftree_copyrename,                      /* -ftree-copyrename */
  OPT_ftree_dce,                             /* -ftree-dce */
  OPT_ftree_dominator_opts,                  /* -ftree-dominator-opts */
  OPT_ftree_dse,                             /* -ftree-dse */
  OPT_ftree_fre,                             /* -ftree-fre */
  OPT_ftree_loop_im,                         /* -ftree-loop-im */
  OPT_ftree_loop_ivcanon,                    /* -ftree-loop-ivcanon */
  OPT_ftree_loop_linear,                     /* -ftree-loop-linear */
  OPT_ftree_loop_optimize,                   /* -ftree-loop-optimize */
  OPT_ftree_lrs,                             /* -ftree-lrs */
  OPT_ftree_pre,                             /* -ftree-pre */
  OPT_ftree_salias,                          /* -ftree-salias */
  OPT_ftree_sink,                            /* -ftree-sink */
  OPT_ftree_sra,                             /* -ftree-sra */
  OPT_ftree_store_ccp,                       /* -ftree-store-ccp */
  OPT_ftree_store_copy_prop,                 /* -ftree-store-copy-prop */
  OPT_ftree_ter,                             /* -ftree-ter */
  OPT_ftree_vect_loop_version,               /* -ftree-vect-loop-version */
  OPT_ftree_vectorize,                       /* -ftree-vectorize */
  OPT_ftree_vectorizer_verbose_,             /* -ftree-vectorizer-verbose= */
  OPT_ftree_vrp,                             /* -ftree-vrp */
  OPT_funit_at_a_time,                       /* -funit-at-a-time */
  OPT_funroll_all_loops,                     /* -funroll-all-loops */
  OPT_funroll_loops,                         /* -funroll-loops */
  OPT_funsafe_loop_optimizations,            /* -funsafe-loop-optimizations */
  OPT_funsafe_math_optimizations,            /* -funsafe-math-optimizations */
  OPT_funsigned_bitfields,                   /* -funsigned-bitfields */
  OPT_funsigned_char,                        /* -funsigned-char */
  OPT_funswitch_loops,                       /* -funswitch-loops */
  OPT_funwind_tables,                        /* -funwind-tables */
  OPT_fuse_cxa_atexit,                       /* -fuse-cxa-atexit */
  OPT_fuse_cxa_get_exception_ptr,            /* -fuse-cxa-get-exception-ptr */
  OPT_fvar_tracking,                         /* -fvar-tracking */
  OPT_fvariable_expansion_in_unroller,       /* -fvariable-expansion-in-unroller */
  OPT_fverbose_asm,                          /* -fverbose-asm */
  OPT_fvisibility_inlines_hidden,            /* -fvisibility-inlines-hidden */
  OPT_fvisibility_,                          /* -fvisibility= */
  OPT_fvpt,                                  /* -fvpt */
  OPT_fvtable_gc,                            /* -fvtable-gc */
  OPT_fvtable_thunks,                        /* -fvtable-thunks */
  OPT_fweak,                                 /* -fweak */
  OPT_fweb,                                  /* -fweb */
  OPT_fwhole_program,                        /* -fwhole-program */
  OPT_fwide_exec_charset_,                   /* -fwide-exec-charset= */
  OPT_fworking_directory,                    /* -fworking-directory */
  OPT_fwrapv,                                /* -fwrapv */
  OPT_fxref,                                 /* -fxref */
  OPT_fzero_initialized_in_bss,              /* -fzero-initialized-in-bss */
  OPT_fzero_link,                            /* -fzero-link */
  OPT_g,                                     /* -g */
  OPT_gcoff,                                 /* -gcoff */
  OPT_gdwarf_2,                              /* -gdwarf-2 */
  OPT_gen_decls,                             /* -gen-decls */
  OPT_ggdb,                                  /* -ggdb */
  OPT_gstabs,                                /* -gstabs */
  OPT_gstabs_,                               /* -gstabs+ */
  OPT_gvms,                                  /* -gvms */
  OPT_gxcoff,                                /* -gxcoff */
  OPT_gxcoff_,                               /* -gxcoff+ */
  OPT_idirafter,                             /* -idirafter */
  OPT_imacros,                               /* -imacros */
  OPT_imultilib,                             /* -imultilib */
  OPT_include,                               /* -include */
  OPT_iprefix,                               /* -iprefix */
  OPT_iquote,                                /* -iquote */
  OPT_isysroot,                              /* -isysroot */
  OPT_isystem,                               /* -isystem */
  OPT_iwithprefix,                           /* -iwithprefix */
  OPT_iwithprefixbefore,                     /* -iwithprefixbefore */
  OPT_lang_asm,                              /* -lang-asm */
  OPT_lang_fortran,                          /* -lang-fortran */
  OPT_lang_objc,                             /* -lang-objc */
  OPT_m128bit_long_double,                   /* -m128bit-long-double */
  OPT_m32,                                   /* -m32 */
  OPT_m386,                                  /* -m386 */
  OPT_m3dnow,                                /* -m3dnow */
  OPT_m486,                                  /* -m486 */
  OPT_m64,                                   /* -m64 */
  OPT_m80387,                                /* -m80387 */
  OPT_m96bit_long_double,                    /* -m96bit-long-double */
  OPT_maccumulate_outgoing_args,             /* -maccumulate-outgoing-args */
  OPT_maes,                                  /* -maes */
  OPT_malign_double,                         /* -malign-double */
  OPT_malign_functions_,                     /* -malign-functions= */
  OPT_malign_jumps_,                         /* -malign-jumps= */
  OPT_malign_loops_,                         /* -malign-loops= */
  OPT_malign_stringops,                      /* -malign-stringops */
  OPT_march_,                                /* -march= */
  OPT_masm_,                                 /* -masm= */
  OPT_mavx,                                  /* -mavx */
  OPT_mbranch_cost_,                         /* -mbranch-cost= */
  OPT_mcmodel_,                              /* -mcmodel= */
  OPT_mdebug_addr,                           /* -mdebug-addr */
  OPT_mdebug_arg,                            /* -mdebug-arg */
  OPT_mfancy_math_387,                       /* -mfancy-math-387 */
  OPT_mfma4,                                 /* -mfma4 */
  OPT_mfp_ret_in_387,                        /* -mfp-ret-in-387 */
  OPT_mfpmath_,                              /* -mfpmath= */
  OPT_mglibc,                                /* -mglibc */
  OPT_mhard_float,                           /* -mhard-float */
  OPT_mieee_fp,                              /* -mieee-fp */
  OPT_minline_all_stringops,                 /* -minline-all-stringops */
  OPT_mintel_syntax,                         /* -mintel-syntax */
  OPT_mlarge_data_threshold_,                /* -mlarge-data-threshold= */
  OPT_mlong_long,                            /* -mlong-long */
  OPT_mmmx,                                  /* -mmmx */
  OPT_mms_bitfields,                         /* -mms-bitfields */
  OPT_mno_align_stringops,                   /* -mno-align-stringops */
  OPT_mno_avx,                               /* -mno-avx */
  OPT_mno_fancy_math_387,                    /* -mno-fancy-math-387 */
  OPT_mno_fma4,                              /* -mno-fma4 */
  OPT_mno_push_args,                         /* -mno-push-args */
  OPT_mno_red_zone,                          /* -mno-red-zone */
  OPT_mno_xfc,                               /* -mno-xfc */
  OPT_mno_xop,                               /* -mno-xop */
  OPT_momit_leaf_frame_pointer,              /* -momit-leaf-frame-pointer */
  OPT_mpclmul,                               /* -mpclmul */
  OPT_mpentium,                              /* -mpentium */
  OPT_mpentiumpro,                           /* -mpentiumpro */
  OPT_mpreferred_stack_boundary_,            /* -mpreferred-stack-boundary= */
  OPT_mpush_args,                            /* -mpush-args */
  OPT_mred_zone,                             /* -mred-zone */
  OPT_mregparm_,                             /* -mregparm= */
  OPT_mrtd,                                  /* -mrtd */
  OPT_msoft_float,                           /* -msoft-float */
  OPT_msse,                                  /* -msse */
  OPT_msse2,                                 /* -msse2 */
  OPT_msse3,                                 /* -msse3 */
  OPT_msse4,                                 /* -msse4 */
  OPT_msse4_1,                               /* -msse4.1 */
  OPT_msse4_2,                               /* -msse4.2 */
  OPT_msse4a,                                /* -msse4a */
  OPT_msseregparm,                           /* -msseregparm */
  OPT_mssse3,                                /* -mssse3 */
  OPT_mstack_arg_probe,                      /* -mstack-arg-probe */
  OPT_mstackrealign,                         /* -mstackrealign */
  OPT_msvr3_shlib,                           /* -msvr3-shlib */
  OPT_mtls_dialect_,                         /* -mtls-dialect= */
  OPT_mtls_direct_seg_refs,                  /* -mtls-direct-seg-refs */
  OPT_mtune_,                                /* -mtune= */
  OPT_muclibc,                               /* -muclibc */
  OPT_mxfc,                                  /* -mxfc */
  OPT_mxop,                                  /* -mxop */
  OPT_nostdinc,                              /* -nostdinc */
  OPT_nostdinc__,                            /* -nostdinc++ */
  OPT_o,                                     /* -o */
  OPT_p,                                     /* -p */
  OPT_pedantic,                              /* -pedantic */
  OPT_pedantic_errors,                       /* -pedantic-errors */
  OPT_print_objc_runtime_info,               /* -print-objc-runtime-info */
  OPT_print_pch_checksum,                    /* -print-pch-checksum */
  OPT_quiet,                                 /* -quiet */
  OPT_remap,                                 /* -remap */
  OPT_spinfile,                              /* -spinfile */
  OPT_std_c__98,                             /* -std=c++98 */
  OPT_std_c89,                               /* -std=c89 */
  OPT_std_c99,                               /* -std=c99 */
  OPT_std_c9x,                               /* -std=c9x */
  OPT_std_gnu__98,                           /* -std=gnu++98 */
  OPT_std_gnu89,                             /* -std=gnu89 */
  OPT_std_gnu99,                             /* -std=gnu99 */
  OPT_std_gnu9x,                             /* -std=gnu9x */
  OPT_std_iso9899_1990,                      /* -std=iso9899:1990 */
  OPT_std_iso9899_199409,                    /* -std=iso9899:199409 */
  OPT_std_iso9899_1999,                      /* -std=iso9899:1999 */
  OPT_std_iso9899_199x,                      /* -std=iso9899:199x */
  OPT_traditional_cpp,                       /* -traditional-cpp */
  OPT_trigraphs,                             /* -trigraphs */
  OPT_undef,                                 /* -undef */
  OPT_v,                                     /* -v */
  OPT_version,                               /* -version */
  OPT_w,                                     /* -w */
  N_OPTS
};

#endif /* OPTIONS_H */
