#!/bin/sh

# Clobber everything excpet the CONFIGURE FILE
rm -rf *-linux-gnu libcpp fixincludes libiberty gcc intl libdecnumber open64-gcc-4.2.0
rm -f libgspin*.a
rm -f config.cache config.log config.status serdep.tmp Makefile

