#include <stdio.h>

static struct libu_msg_rec {
	int msg_id;
	char *msg;
} libu_default_msgs[] = {
	{ 4001, "A READ operation tried to read past the end-of-file." },
	{ 4002, "A READ operation tried to read an empty file." },
	{ 4003, "A READ is invalid when a file is positioned after the end-of-file." },
	{ 4004, "A namelist READ operation tried to read past the end-of-file." },
	{ 4005, "A READ operation on an internal file tried to read past the end-of-file." },
	{ 4006, "An end-of-record condition occurred when processing a nonadvancing READ statement." },
	{ 4010, "The unit number (%d) must be nonnegative." },
	{ 4011, "The unit number (%d) in the OPEN statement must be nonnegative and outside\n  the range of 100 through 102." },
	{ 4012, "The unit number (%lld) must be nonnegative." },
	{ 4013, "The unit number (%lld) in the OPEN statement must be nonnegative and outside\n  the range of 100 through 102." },
	{ 4014, "The requested action requires that unit %lld be connected to a file." },
	{ 4015, "The record number (%lld) must be a positive (nonzero) integer." },
	{ 4016, "A READ operation tried to read a nonexistent record (%lld)." },
	{ 4021, "The unit is not connected for direct access; use an OPEN statement." },
	{ 4022, "The requested action requires that the unit be connected to a tape file." },
	{ 4023, "The requested action requires that unit %d be connected to a file." },
	{ 4024, "The named file cannot be opened. The maximum number of named files is already open." },
	{ 4025, "The open failed because the file is already open for a different type of I/O." },
	{ 4026, "The open failed because the file is already opened for a different type of I/O." },
	{ 4027, "The system file permissions are incompatible with the ACTION specifier value\n  in the OPEN statement." },
	{ 4028, "The file does not support automatic skipping of bad data." },
	{ 4029, "An underlying C library read or write request failed." },
	{ 4030, "The STATUS specified on OPEN must be 'OLD', 'NEW', 'SCRATCH', or 'UNKNOWN'." },
	{ 4031, "The ACCESS specified on OPEN must be 'SEQUENTIAL' or 'DIRECT'." },
	{ 4032, "The FORM specified on OPEN must be 'FORMATTED' or 'UNFORMATTED'." },
	{ 4033, "The RECL specified on OPEN must be a positive (nonzero) integer." },
	{ 4034, "The BLANK specifier on OPEN must be 'NULL' or 'ZERO'." },
	{ 4035, "The POSITION specified on OPEN must be 'REWIND', 'APPEND', or 'ASIS'." },
	{ 4038, "The ACTION specifier on OPEN must be 'READ', 'WRITE', or 'READWRITE'." },
	{ 4039, "The DELIM specifier on OPEN must be 'QUOTE', 'APOSTROPHE', or 'NONE'." },
	{ 4040, "A FILE specifier is required on OPEN if STATUS is 'OLD', 'NEW', or 'REPLACE'." },
	{ 4041, "A FILE specifier is invalid on OPEN if STATUS is 'SCRATCH'." },
	{ 4042, "A RECL specifier is required on OPEN of a direct-access file." },
	{ 4044, "A BLANK specifier is invalid on OPEN of an unformatted file." },
	{ 4045, "A POSITION specifier is invalid on OPEN of a direct-access file." },
	{ 4046, "The assign and asgcmd commands are in conflict." },
	{ 4047, "Concurrent assigns to unit %d and file '%s' are in conflict." },
	{ 4048, "The PAD specifier on OPEN must be 'YES' or 'NO'." },
	{ 4049, "A DELIM specifier is invalid in an OPEN of an unformatted file." },
	{ 4050, "The file must exist prior to OPEN if STATUS is 'OLD'." },
	{ 4051, "The file must not exist prior to OPEN if STATUS is 'NEW'." },
	{ 4052, "The specified file is already connected to another unit." },
	{ 4054, "Only the BLANK, DELIM and PAD specifiers may be changed on an OPEN of an opened file." },
	{ 4055, "The file cannot be opened (%s file structure does not support\n  %s %s access)." },
	{ 4056, "Direct access is not allowed with the specified -s or -F\n  assign/asgcmd option." },
	{ 4057, "The file cannot be opened (FFIO options do not support this type of OPEN)." },
	{ 4058, "STATUS specifier must not be NEW on an OPEN of an opened unit." },
	{ 4059, "An incorrect RECL was specified for an existing direct-access file." },
	{ 4060, "A standard file cannot be opened as an unformatted, direct-access, or\n  nontext file." },
	{ 4061, "An invalid AQPSIZE parameter was specified in AQOPEN." },
	{ 4062, "The FILE specifier on OPEN of unit %d conflicts with the -a or -D\n  assign attribute." },
	{ 4063, "The program tried to open too many word-addressable files." },
	{ 4064, "The buffer size for a word-addressable file exceeds the maximum." },
	{ 4065, "Truncation after write may not be suppressed for this file." },
	{ 4066, "Truncation after write is not supported for this file type." },
	{ 4067, "A PAD specifier is invalid in an OPEN of an unformatted file." },
	{ 4068, "The file cannot be opened for UNFORMATTED I/O." },
	{ 4069, "The file cannot be opened for FORMATTED I/O." },
	{ 4070, "The STATUS specified on a CLOSE must be 'KEEP' or 'DELETE'." },
	{ 4071, "A STATUS specifier of 'KEEP' is invalid on a CLOSE of a scratch file." },
	{ 4072, "The increment value on an implied do loop is zero." },
	{ 4073, "An AQIO routine was called with an invalid file handle." },
	{ 4074, "The specified file is connected to another unit which does not have the\n  \"-m on\" assign attribute." },
	{ 4075, "The file type does not support the \"%s\" assign attribute." },
	{ 4076, "A Fortran unit cannot be both private and global." },
	{ 4077, "The specified Fortran unit cannot be assigned -P global." },
	{ 4078, "The specified Fortran unit cannot be private to a thread." },
	{ 4079, "A BACKSPACE requires read permission for the file." },
	{ 4080, "A formatted read or write is not allowed on an unformatted file." },
	{ 4081, "An unformatted read or write is not allowed on a formatted file." },
	{ 4082, "A direct access read or write is not allowed on a sequential-access file." },
	{ 4083, "A sequential access read or write is not allowed on a direct-access file." },
	{ 4084, "A BACKSPACE is invalid on a direct-access file." },
	{ 4085, "An ENDFILE is invalid on a direct-access file." },
	{ 4086, "A REWIND is invalid on a direct-access file." },
	{ 4087, "A read after write is invalid on a sequential-access file." },
	{ 4088, "The record number (%d) must be a positive (nonzero) integer." },
	{ 4090, "A READ operation was attempted on a file with no read permission." },
	{ 4091, "A WRITE operation was attempted on a file with no write permission." },
	{ 4092, "The file does not support a BACKSPACE operation." },
	{ 4093, "The file does not support an ENDFILE operation." },
	{ 4094, "The file does not support a REWIND operation." },
	{ 4095, "A WRITE operation is invalid if the file is positioned after the end-of-file." },
	{ 4096, "An ENDFILE is invalid if the file is positioned after the end-of-file." },
	{ 4097, "A READ operation tried to read a nonexistent record (%d)." },
	{ 4098, "A BACKSPACE is invalid on a piped file." },
	{ 4099, "A REWIND is invalid on a piped file." },
	{ 4100, "A READ operation tried to read a nonexistent record." },
	{ 4101, "The file could not be deleted while executing the CLOSE statement." },
	{ 4103, "The specified Fortran unit may not be private to a thread." },
	{ 4104, "The specified Fortran unit may not be global to an application team" },
	{ 4117, "The format and specified I/O list produce an infinite loop." },
	{ 4118, "A literal string is invalid in an input format." },
	{ 4119, "The Q data edit-descriptor is invalid in an output format." },
	{ 4140, "The file does not support a SKIPF operation." },
	{ 4170, "An input list item is incompatible with its data edit-descriptor." },
	{ 4171, "An output list item is incompatible with its data edit-descriptor." },
	{ 4173, "The input field for a logical variable is invalid." },
	{ 4180, "The input on a READ statement with list-directed formatting was unrecognized." },
	{ 4181, "A misformed complex number was encountered on a list-directed READ." },
	{ 4182, "A string is too long for READ with list-directed formatting." },
	{ 4190, "A numeric input field contains an invalid character." },
	{ 4191, "An overflow occurred during the conversion of fixed-point (integer) input data." },
	{ 4192, "An underflow occurred during the conversion of floating-point input data." },
	{ 4193, "An overflow occurred during the conversion of floating-point input data." },
	{ 4194, "A numeric input field has incomplete data." },
	{ 4201, "A READ operation tried to read past the end-of-record." },
	{ 4202, "The program read or wrote less data than was requested." },
	{ 4203, "The program was unable to request more memory space during a\n  formatted READ statement." },
	{ 4205, "The program was unable to request more memory space." },
	{ 4206, "The program was unable to request more SDS space." },
	{ 4208, "An I/O statement was invoked while another was active." },
	{ 4209, "You must specify the file size when using 'assign -a SDS'." },
	{ 4211, "A WRITE operation tried to write a record that was too long." },
	{ 4212, "An internal WRITE tried to write beyond the end of an internal file." },
	{ 4213, "A pointer or allocatable array in an I/O list has not been associated\n  or allocated." },
	{ 4214, "A pointer or allocatable array used as a format specifier has not been\n associated or allocated." },
	{ 4215, "A pointer or allocatable array used as an internal file has not been\n associated or allocated." },
	{ 4216, "A zero-sized array or scalar was used as a format specifier." },
	{ 4217, "A formatted READ operation encountered a malformed record." },
	{ 4220, "An internal library run-time error has occurred." },
	{ 4221, "An internal Fortran unit table contains an unknown file structure." },
	{ 4223, "An unknown data type was passed to the library from the compiler." },
	{ 4224, "A preprocessed format contained an invalid format code." },
	{ 4226, "An internal error occurred on a tape read." },
	{ 4295, "Empty parentheses followed character variable \"%s\" in\n  namelist input record." },
	{ 4296, "Substring value of character variable \"%s\" in\n  namelist input record must be numeric." },
	{ 4297, "Empty parentheses followed array \"%s\" in\n  namelist input record." },
	{ 4298, "Character between subscripts of array \"%s\" in\n  namelist input record must be a comma." },
	{ 4299, "Subscript value of array \"%s\" in namelist\n  input record must be numeric." },
	{ 4303, "Namelist variable name \"%s\" is longer\n  than 63 characters." },
	{ 4304, "Namelist input group name \"%s\" does not\n  match READ group name. " },
	{ 4305, "Integer namelist variable \"%s\" equivalenced\n  to floating point data." },
	{ 4306, "The leading character of a NAMELIST name or termination was unrecognized." },
	{ 4307, "Incorrect namelist input variable \"%s\" or\n  mismatched input value." },
	{ 4308, "A character variable declared as zero length appeared in namelist input." },
	{ 4309, "Array section \"%s\" in nonstandard namelist\n  input is not allowed." },
	{ 4310, "An error occurred on a namelist READ operation." },
	{ 4312, "An invalid character was passed to a namelist output control routine." },
	{ 4313, "A namelist variable name must consist of fewer than 64 characters." },
	{ 4314, "The namelist input group name does not match the name being sought. " },
	{ 4315, "The variable name \"%s\" is not a member of the\n  current namelist group." },
	{ 4316, "The namelist input is missing an equal (=) separator." },
	{ 4317, "A namelist variable is equivalenced to invalid logical data." },
	{ 4318, "A namelist variable is equivalenced to invalid complex data." },
	{ 4320, "The input record is too long for a namelist READ." },
	{ 4321, "A namelist read was attempted for a variable outside an array boundary." },
	{ 4323, "Too many namelist elements were specified." },
	{ 4324, "The variable name '%s' is unrecognized in namelist input." },
	{ 4325, "The namelist variable \"%s\" is equivalenced to data of the wrong type.\n  This variable is declared type \"%s\"." },
	{ 4326, "The namelist name is larger than the size of the output record." },
	{ 4327, "Complex(kind=16) data must be accessed in namelist I/O from an F90 file." },
	{ 4328, "Structure data must be accessed in namelist I/O from a CF90 file." },
	{ 4329, "A nonblank character precedes the ampersand indicating a namelist group name." },
	{ 4330, "A direct access file cannot be used with %s." },
	{ 4331, "A formatted file cannot be used with %s." },
	{ 4332, "The starting address is greater than the ending address on a %s." },
	{ 4334, "The position argument to SETPOS is invalid." },
	{ 4335, "The requested positioning operation is not supported." },
	{ 4339, "Fortran I/O statements cannot be used while a file is open for\n  nonstandard types of I/O." },
	{ 4340, "The DECODE record length must be between 1 and the maximum record length." },
	{ 4341, "The ENCODE record length must be between 1 and the maximum record length." },
	{ 4342, "An invalid mixture of data types is being used." },
	{ 4343, "The value of the ADVANCE= specifier on a READ or WRITE statement was not \n  'YES' or 'NO'." },
	{ 4344, "The SIZE= specifier was provided on a READ statement without the\n  ADVANCE='NO' specifier." },
	{ 4345, "A EOR= specifier was provided on a READ statement without ADVANCE='NO'." },
	{ 4350, "A negative tape block number is invalid." },
	{ 4351, "The NBS parameter on a tape positioning request is invalid." },
	{ 4352, "The NVS parameter on a tape positioning request is invalid." },
	{ 4354, "The tape block size exceeds the maximum allowed." },
	{ 4355, "This combination of tape positioning parameters is invalid." },
	{ 4356, "A READ operation encountered an unrecovered tape error." },
	{ 4357, "A SKIPF operation could not be performed. " },
	{ 4358, "The NV parameter on a tape positioning request is invalid." },
	{ 4360, "Invalid number of arguments passed to library routine \"%s\"." },
	{ 4361, "NTAB not in the range 1<=NTAB<=64 for library routine \"%s\"." },
	{ 4362, "Invalid table number passed to library routine \"%s\"." },
	{ 4363, "Increment specified would make table length negative for routine \"%s\"." },
	{ 4370, "The reading or writing of partial word data is not supported on this file." },
	{ 4371, "Implicit data conversion for the specified unit cannot be performed\n  because the selected foreign data conversion is disabled." },
	{ 4372, "Unformatted I/O encountered an I/O list item of type %s%s.\n  The current implicit data conversion does not support this data type." },
	{ 4373, "An I/O list contains a variable with an unsupported type and kind." },
	{ 4374, "Shared variables are unsupported for this type of I/O." },
	{ 4375, "Data conversion is not supported on this type of file." },
	{ 4380, "Invalid call to library routine \"%s\". " },
	{ 4391, "The READ or READP routine received a system error 1." },
	{ 4392, "The READ or READP routine received a system error 2." },
	{ 4393, "The READ or READP routine received a system error 3." },
	{ 4394, "The READ or READP routine received a system error 4." },
	{ 4402, "Invalid call to library routine \"%s\"; %d argument(s) were passed,\n  but %s argument(s) are required." },
	{ 4403, "For the entry '%s', called from '%s' at line %d:\n  Shape mismatch for argument \"%s\".\n    actual argument is %s\n    dummy  argument is %s" },
	{ 4405, "Illegal value for DIM argument to an array intrinsic function." },
	{ 4406, "Illegal rank for matrix argument to MATMUL array intrinsic." },
	{ 4407, "Matrix arguments to MATMUL array intrinsic are not conformable." },
	{ 4408, "Size of SOURCE array for RESHAPE array intrinsic is less than size\n  of SHAPE array when PAD argument is zero or is not present. " },
	{ 4409, "The SHAPE array for the RESHAPE array intrinsic function contains\n  a negative value." },
	{ 4410, "An inquiry function argument is a disassociated pointer or an\n  unallocated array." },
	{ 4411, "An allocatable array in the ALLOCATE statement is already allocated." },
	{ 4412, "An argument in the DEALLOCATE statement is a disassociated pointer or an\nunallocated array." },
	{ 4413, "An argument in the DEALLOCATE statement points to a portion of the original\n allocation. " },
	{ 4414, "The ncopies argument to the REPEAT function is negative." },
	{ 4415, "The S argument to the NEAREST function is zero." },
	{ 4416, "A zero integer base is being raised to a zero integer power." },
	{ 4417, "ORDER argument to the RESHAPE function contains illegal values." },
	{ 4418, "Result of TRANSFER intrinsic with no SIZ argument smaller than source." },
	{ 4419, "SHAPE argument to RESHAPE function is zero sized array." },
	{ 4420, "The VECTOR argument to UNPACK function contains insufficient values\n  for the true elements of the MASK array argument." },
	{ 4421, "Array %s is scoped GETFIRST starting in %s at line %d,\n  but has no associated storage on entry to the taskloop." },
	{ 4422, "A DEALLOCATE statement argument points to a portion of the\n original allocation.\n  Original size in bytes for the argument is %d\n  Current size in bytes for the argument is %d" },
	{ 4423, "An argument to inquiry function %s is a disassociated\n  pointer or an unallocated array." },
	{ 4424, "Illegal value for DIM argument to array intrinsic %s." },
	{ 4500, "The assign environment file cannot be read; check read permissions\n  or reassign the FILENV environment variable." },
	{ 4501, "The assign environment file cannot be written; check write permissions\n   or reassign the FILENV environment variable." },
	{ 4503, "Attributes in the assign environment file have an unreadable format." },
	{ 4504, "The value on assign option -%c is invalid." },
	{ 4505, "Value %s on assign option -%c is invalid." },
	{ 4506, "Assign option -%c is unrecognized." },
	{ 4507, "The option value \"%s\" for assign option -s is not supported." },
	{ 4508, "Assign options -F and -s cannot be specified together." },
	{ 4509, "Assign option -F cannot be specified with options -b, -o, or -u." },
	{ 4510, "Assign options -N and -C require that option -F also be specified." },
	{ 4511, "The IVALUE argument passed to ASNCTL is invalid." },
	{ 4512, "Local assign is already in effect and cannot be specified again." },
	{ 4513, "An unrecognized assign object was specified; valid assign object\n  prefixes are f: and u:." },
	{ 4514, "An assign to a file name may not use the u: prefix." },
	{ 4515, "Assign options -I and -O cannot be specified together." },
	{ 4516, "Assign options -R and -V cannot be specified together." },
	{ 4517, "Assign option -R cannot be specified with other options." },
	{ 4518, "Assign option -V cannot be specified with other options." },
	{ 4519, "More than one assign object was specified." },
	{ 4520, "At least one assign object must be specified." },
	{ 4521, "The assign to file '%s' conflicts with the assign to unit %d." },
	{ 4522, "An internal library error occurred while reading a UNICOS 5.0 assign\n  environment file." },
	{ 4523, "An unrecognized directive was passed to the ASSIGN routine or was\n  encountered in the assign environment file." },
	{ 4524, "The file name passed to the assign command or ASNFILE has an embedded\n  blank." },
	{ 4525, "Value portion %s of the -p option cannot be processed.  A list\n  or range of file system stripe partition numbers should be specified\n  in the form '1:3', '0-4', or '0:3-4'." },
	{ 4526, "Assign option -c requires that option -n also be specified." },
	{ 4527, "Assign processing requires that environment variable FILENV be set when\n  environment variable TMPDIR is not set." },
	{ 4528, "Cannot restore assign environment because assign environment stack is empty." },
	{ 4529, "The -a and -D assign options may not both be assigned to a unit or file name." },
	{ 4530, "The Fortran character variable passed to ASNQFILE or ASNQUNIT is too short." },
	{ 4531, "Line %d in the assign environment file has an unrecognized format." },
	{ 4532, "Assign record %d in the assign environment has an unrecognized format:\n   \"%s\"" },
	{ 4533, "FILENV contains a null environment variable name." },
	{ 4534, "The file name %s matches more than one filename pattern in\n  the assign environment." },
	{ 4535, "The \"-T on\" assign attribute may not be specified with \"-m on\"." },
	{ 4536, "Assign processing requires that environment variable FILENV be set." },
	{ 4537, "The FFIO file structure %s is invalid." },
	{ 4538, "The FFIO option '%s' is invalid for file structure\n '%s'." },
	{ 4539, "The FFIO option '%s' conflicts with another option \nspecified for this file structure." },
	{ 4540, "The FFIO option '%s' is not correctly specified." },
	{ 4541, "The FFIO specification '%s' is incomplete." },
	{ 4542, "The FFIO specification '%s' is too long." },
	{ 4543, "The unit specification in the FFIO option '%s' is\ninvalid." },
	{ 4544, "The maximum block size in the FFIO specification is\ninvalid." },
	{ 4545, "The FFIO numeric parameters %d and %d are an invalid combination." },
	{ 4546, "The record size in the FFIO specification is invalid." },
	{ 4547, "The record format in the FFIO specification is invalid." },
	{ 4548, "A numeric value is required for '%s' when FFIO options\n'%s' and '%s' are specified." },
	{ 4549, "The numeric value %d exceeds the maximum allowed (%d)\nfor %s." },
	{ 4550, "The numeric value %d is less than the minimum allowed \n(%d) for %s." },
	{ 4551, "The FFIO specification contains too many layers." },
	{ 4552, "The value on assign option %s is invalid." },
	{ 4553, "Value %s on assign option %s is invalid." },
	{ 4554, "Assign option %s is unrecognized." },
	{ 4555, "The \"-l\" assign option may not be specified with \"-o_raw\" or \"-o_ldraw\"." },
	{ 4580, "Assign option %s is not supported.  This option will be ignored." },
	{ 4583, "Option '-s sbin' may not be supported in future UNICOS releases.\n  Use '-s unblocked' or '-F system' for unformatted files and '-s text' for\n  formatted files." },
	{ 4584, "Assign option -p requires that -n also be specified;  without the -n\n option, -p will be ignored." },
	{ 4585, "Assign option -r will not be supported in future releases.  Use\n  option -p instead." },
	{ 4586, "The assign options sequence '-a SDS -s u -n x' may not be supported in future\n  UNICOS releases.  Use '-F sds:x -T off' to get an SDS file with no truncation." },
	{ 4587, "Assign option '-u' is valid only with file types 'unblocked', 'tape',\n  'bmx', 'tape50' or 'bmx50'.  If a different file type is\n  specified, the -u option will be ignored." },
	{ 4588, "Assign option -V is ignored when specified with other options.  This\n  will be an error in future UNICOS releases." },
	{ 4589, "The -q assign option value (%d) overrides the stride from the\n-n assign attribute (%d).  The -q attribute value will be used." },
	{ 4590, "The FFIO specification contains too many numeric parameters.\n'%d' parameters will be used; excess parameters will be ignored." },
	{ 4611, "Missing opening (left) parenthesis in format." },
	{ 4612, "Missing closing (right) parenthesis in format." },
	{ 4613, "Missing numeric field in format." },
	{ 4614, "Period expected in format data edit-descriptor." },
	{ 4615, "A signed value is incorrectly placed in the format." },
	{ 4616, "A repetition count is incorrectly placed in the format." },
	{ 4617, "A zero repetition count is invalid in a format." },
	{ 4618, "A zero length field width is invalid in a format." },
	{ 4619, "A field is too large in a format." },
	{ 4620, "A Hollerith edit-descriptor has a zero or missing count." },
	{ 4621, "A format contained an unknown edit-descriptor." },
	{ 4622, "The format contains an unterminated literal string." },
	{ 4623, "The program was unable to obtain more memory while processing a format." },
	{ 4691, "The PACK or UNPACK routine was called with too few arguments." },
	{ 4692, "The PACK or UNPACK routine was called with a negative COUNT." },
	{ 4693, "The PACK or UNPACK routine was called with an invalid NBITS." },
	{ 4800, "A BMM simulation routine was called with a \n  VL (vector length) that is not valid. The maximum supported VL is 64." },
	{ 4850, "An invalid constant, structure, or component name was \n  passed to a subroutine or function." },
	{ 4851, "A handle could not be created." },
	{ 4852, "An output character parameter was truncated." },
	{ 4853, "Too many array elements to be returned." },
	{ 4854, "The end of file, record, or directory stream has been encountered." },
	{ 4907, "The DEFBUFSIZ environment variable no longer specifies a default buffer size." },
	{ 4931, "For the entry '%s', called from '%s' at line %d:\n  Kind type conflict for Call\n  '%s' was called as kind type %d\n  '%s' is defined as kind type %d" },
	{ 4932, "For the entry '%s', called from '%s' at line %d:\n  Rank conflict for Call\n  '%s' was called as rank %d\n  '%s' is defined as rank %d" },
	{ 4933, "For the entry '%s', called from '%s' at line %d:\n  Array size conflict for Call\n  '%s' was called with total array size %d\n  '%s' is defined with total array size %d" },
	{ 4934, "For the entry '%s', called from '%s' at line %d:\n  Character length conflict for Call\n  '%s' was called with character length %d\n  '%s' is defined with character length %d" },
	{ 4935, "For the entry '%s', called from '%s' at line %d:\n  Derived types do not match for Call." },
	{ 4936, "For the entry '%s', called from '%s' at line %d:\n  Interface conflict for Call.  '%s' was called as a\n  POINTER function but does not have the POINTER attribute." },
	{ 4937, "For the entry '%s', called from '%s' at line %d:\n  Interface conflict for Call.  '%s' has the\n  POINTER attribute but was not called as a POINTER function." },
	{ 4938, "For the entry '%s', called from '%s' at line %d:\n  Interface conflict for Call\n  Argument number %d is not PRESENT but is not optional." },
	{ 4939, "For the entry '%s', called from '%s' at line %d:\n  Kind type conflict for Argument number %d\n  Actual argument kind type is kind type %d\n  Dummy argument kind type  is kind type %d" },
	{ 4940, "For the entry '%s', called from '%s' at line %d:\n  Type conflict for Argument number %d.  Derived types do not match." },
	{ 4941, "For the entry '%s', called from '%s' at line %d:\n  Dummy argument number %d has INTENT(OUT) or INTENT(INOUT)\n  but the actual argument is not definable. " },
	{ 4942, "For the entry '%s', called from '%s' at line %d:\n  Interface conflict for Call\n  Dummy argument number %d has the POINTER attribute\n  but the actual argument is not a POINTER. " },
	{ 4943, "For the entry '%s', called from '%s' at line %d:\n  Rank conflict for POINTER/ASSUMED SHAPE argument number %d\n  Actual argument is rank %d.  Dummy argument is rank %d" },
	{ 4944, "For the entry '%s', called from '%s' at line %d:\n  Character length conflict for POINTER/ASSUMED SHAPE argument number %d\n  Character length of actual argument is %d\n  Character length of dummy argument is %d" },
	{ 4945, "For the entry '%s', called from '%s' at line %d:\n  Interface conflict for Call\n  Dummy argument number %d is an ASSUMED SHAPE array\n  Actual argument number %d is a sequence array or scalar." },
	{ 4946, "For the entry '%s', called from '%s' at line %d:\n  Actual argument number %d is an array\n  Dummy argument number %d is a scalar." },
	{ 4947, "For the entry '%s', called from '%s' at line %d:\n  Character length of dummy argument number %d is greater\n  than the character length of the actual argument\n  Character length of actual argument is %d\n  Character length of dummy argument is %d" },
	{ 4948, "For the entry '%s', called from '%s' at line %d:\n  Actual argument number %d is a scalar and not an array element\n  Dummy argument number %d is an array" },
	{ 4949, "For the entry '%s', called from '%s' at line %d:\n  Total array size of dummy argument number %d is greater\n  than the total array size of the actual argument\n  Total array size of actual argument is %d\n  Total array size of dummy argument is %d" },
	{ 4950, "At line %d in Fortran routine '%s', subscript value %d\n  is out of bounds for array '%.*s'." },
	{ 4951, "At line %d in Fortran routine '%s', in dimension %d,\n  extents %d and %d are not equal." },
	{ 4952, "For the entry '%s', called from '%s' at line %d:\n  Number of arguments for call, %d, does not equal expected number of\n  arguments %d." },
	{ 4953, "For the entry '%s', called from '%s' at line %d:\n  Type conflict for argument #%d\n  actual argument type =     %s\n  dummy argument type  =     %s" },
	{ 4954, "For the entry '%s', called from '%s' at line %d:\n  Type conflict for Call\n  '%s' was called as %s\n  '%s' is defined as %s" },
	{ 4955, "For the entry '%s', called from '%s' at line %d:\n  Shape mismatch for argument \"%s\".\n    actual argument is %s\n    dummy  argument is %s" },
	{ 4960, "Conformance error for dimension %d at line %d in file '%s'." },
	{ 4961, "Subscript %d is out of range for dimension %d for array\n  '%s' at line %d in file '%s' with bounds %d:%d." },
	{ 4962, "Subscript %d:%d:%d is out of range for dimension %d for array\n  '%s' at line %d in file '%s' with bounds %d:%d." },
	{ 4963, "Substring %d:%d is out of range for character variable '%s'\n  at line %d in file '%s'.  Parent string size is %d." },
	{ 4964, "Subscript is out of range for dimension %d for array\n  '%s' at line %d in file '%s',\n  diagnosed in routine '%s'." },
	{ 4965, "Conformance error for dimension %d at line %d in\n  file '%s'.  Extents %lld and %lld are not equal.\n  Diagnosed in routine '%s'." },
	{ 4966, "Conformance error for a dimension in transformational\n  function reference at line %d in file '%s'.\n  Extents %lld and %lld are not equal.  Diagnosed in routine '%s'." },
	{ 4967, "A disassociated pointer '%s' is referenced at line %d\n  in file '%s'." },
	{ 4968, "An unallocated allocatable array '%s' is referenced at\n  at line %d in file '%s'." },
	{ 4969, "A disassociated assumed shape array '%s' is referenced\n  at line %d in file '%s'." },
	{ 4975, "At line %d in C file '%s', the pointer expression involving\n  '%s' is either less than or equal to zero or exceeds the memory\n  limit of this machine." },
	{ 4976, "At line %d in C file '%s', subscript value %d\n  is out of bounds for dimension %d, which has a size of %d,\n  for array '%s'." },
	{ 5000, "An internal FFIO error has been encountered." },
	{ 5001, "The FFIO layer specification is inconsistent." },
	{ 5002, "This FFIO request is not supported." },
	{ 5003, "The format used requires lower-level record boundaries." },
	{ 5004, "The UBC (unused bit count) is invalid for this FFIO request." },
	{ 5005, "The record format is invalid.  File corruption is possible." },
	{ 5006, "The FFIO file contains an invalid segment control code." },
	{ 5007, "This request exceeds the maximum record size." },
	{ 5008, "This request exceeds the maximum block size." },
	{ 5009, "Read-after-write is invalid on this file type." },
	{ 5010, "A request for more memory has failed." },
	{ 5011, "This FFIO request is invalid." },
	{ 5012, "Numeric conversion of a partial item is invalid." },
	{ 5013, "Writing past EOD (end-of-data) is not permitted." },
	{ 5014, "Reading past EOD (end-of-data) is not permitted." },
	{ 5015, "The block size must be a multiple of record size." },
	{ 5016, "An EOF or EOD has been encountered unexpectedly." },
	{ 5017, "The CDC file contains an invalid block terminator." },
	{ 5018, "The CDC file contains an invalid I control word." },
	{ 5019, "The CDC file contains an invalid W control word." },
	{ 5021, "A write-after-read operation is not yet supported." },
	{ 5022, "The requested FFIO layer has been disabled." },
	{ 5023, "A character conversion operation has failed." },
	{ 5024, "A numeric conversion operation has failed." },
	{ 5025, "The open specification is invalid." },
	{ 5026, "The COS blocked file contains an invalid BCW (block control word)." },
	{ 5027, "The COS blocked file contains an invalid RCW (record control word)." },
	{ 5028, "The device type is wrong for the requested I/O." },
	{ 5029, "The NOS/VE V-format file contains an invalid control word." },
	{ 5030, "An SDS allocation or reallocation operation failed." },
	{ 5031, "An SDS I/O operation (ssread() or sswrite()) failed." },
	{ 5032, "A parameter to an ffseek() operation is invalid." },
	{ 5033, "The COS blocked file has an invalid format." },
	{ 5034, "FSS (fast secondary storage) overflow is not permitted by user request." },
	{ 5035, "The requested layer cannot write an EOF (end-of-file)." },
	{ 5036, "An invalid PRI field has been found in the RCW of a COS blocked file." },
	{ 5037, "An invalid PFI field has been found in the RCW of a COS blocked file." },
	{ 5038, "An FFIO routine was called with insufficient parameters." },
	{ 5039, "GETPOS is not supported for this file specification." },
	{ 5040, "SETPOS is not supported for this file specification." },
	{ 5041, "The file must be positioned on a record boundary to honor this request." },
	{ 5042, "The fd parameter passed to an FFIO routine is invalid." },
	{ 5043, "The number of buffers requested is invalid." },
	{ 5044, "The buffer size requested is invalid." },
	{ 5045, "An underlying FFIO layer is not byte-stream capable." },
	{ 5046, "FSS (fast secondary storage) overflow has failed." },
	{ 5047, "I/O for an SDS-buffered file was attempted to a non-word aligned\n  memory location." },
	{ 5048, "A file has a size which is not a multiple of the FFIO layer's granularity." },
	{ 5049, "An operation on a file has left the file positioned at a location which\n  is not a multiple of the FFIO layer's granularity." },
	{ 5050, "The \"cache.ssd\" and \"cachea.ssd\" FFIO layer specifications require\n  an underlying layer which supports O_SSD." },
	{ 5051, "The file does not reside on an ER90 device." },
	{ 5052, "The O_APPEND flag is unsupported by the specified FFIO layers." },
	{ 5053, "The O_SSD flag is unsupported by the specified FFIO layers." },
	{ 5054, "An internal listio subrequest references more than one FFIO layer." },
	{ 5055, "The file cannot be made scratch by use of fffcntl() with the FC_SCRATCH\nfunction code." },
	{ 5056, "An ER90 file was not assigned an appropriate -F attribute." },
	{ 5057, "A write system call wrote less data than expected." },
	{ 5058, "A read system call read less data than expected." },
	{ 5059, "Stacked shared caches are not supported in multitasked programs." },
	{ 5060, "An FFIO layer has indicated that it cannot handle fflistio requests." },
	{ 5061, "The FFIO layers cannot be properly locked for multitasking." },
	{ 5063, "This specification of stacked shared caches is not supported." },
	{ 5064, "Stacked shared caches are not supported." },
	{ 5065, "End of volume processing is not enabled." },
	{ 5066, "This operation is not allowed while in special eov processing." }
};

/*
 *	libu_defgets - return raw default error message text or NULL if none
 *
 *		msg_num		Message number
 */
char *
libu_defgets(int msg_num)
{
	int i;

	for (i = 0; i < 400; i++)
		if (msg_num == libu_default_msgs[i].msg_id)
			return libu_default_msgs[i].msg;

	return NULL;
}

