
#################################################################
# Entry for the dejagnu testing framework
#  dejagnu will first try to load this file
# In this file, we try to set the configuration globally and 
# some global variables.
#################################################################
# Configuration we are going to use
set conf open64-O2

# Today's date in YYYY-MM-DD format
#set date [clock format [clock scan [system date]] -format "%Y-%m-%d"]
set date [exec date +%F]

# Home for the test framework
if {[info exists env(DEJAGNU)]} {
	set testhome [split $env(DEJAGNU) /]
	set len [expr [llength $testhome] - 1]
	set testhome [join [lreplace $testhome $len $len] /]
} else {
	set testhome [pwd]
	set dejagnu $testhome
	append dejagnu "/site.exp"
	if {[file exists $dejagnu]} {
		set env(DEJAGNU) $dejagnu
	} else {
		puts ""
		puts "******Error:DEJAGNU variable is empty and site.exp doesn't exist in current directory!!"
		puts "Please set DEJAGNU to point to your site.exp file"
		puts ""
		exit
	}
}

# check for TOOLROOT and COMP_TARGET_ROOT
#if {![info exists env(TOOLROOT)]} {
#	puts "******Error: TOOLROOT is not set."
#	exit
#} elseif {![file isdirectory $env(TOOLROOT)]} {
#	puts "******Error: TOOLROOT directory $env(TOOLROOT) doesn't exist."
#	exit
#}
#if {![info exists env(COMP_TARGET_ROOT)]} {
#	puts "******Error: COMP_TARGET_ROOT is not set."
#} elseif {![file isdirectory $env(COMP_TARGET_ROOT)]} {
#	puts "******Error: COMP_TARGET_ROOT directory $env(COMP_TARGET_ROOT) doesn't exist."
#}

# the dir for storing log files
set logdir   $testhome/log/$date/

# the dir for storing historical data
set datdir   $testhome/dat

# the dir for storing configuration files
set confdir  $testhome/conf

# the output for the test cases
set testoutput $testhome/output/$date

# log file for putting compiler update/building
set compiler_build_log $logdir/compiler-build.log
set check_in_log       $logdir/checkin.log

set sim_check_in_log $logdir/sim-checkin.log

set lib_build_log    $logdir/lib-build.log
set lib_check_in_log $logdir/lib-checkin.log

set uclibc_build_log    $logdir/uclibc-build.log
set uclibc_check_in_log $logdir/uclibc-checkin.log

set uclibcxx_build_log    $logdir/uclibc++_build.log
set uclibcxx_check_in_log $logdir/uclibc++_checkin.log

set asld_build_log   $logdir/binutils-build.log
set asld_check_in_log $logdir/binutils-checkin.log

set sl2lib_build_log $logdir/sl2lib_build.log
set sl2lib_check_in_log $logdir/sl2lib_checkin.log

set nucleus_plus_build_log $logdir/nucleus_plus_build.log
set nucleus_plus_check_in_log $logdir/nucleus_plus_check_in.log

set nucleus_plus_spe_build_log $logdir/nucleus_plus_spe_build.log
set nucleus_plus_spe_check_in_log $logdir/nucleus_plus_spe_check_in.log

set slgdb_build_log $logdir/slgdb_build.log
set slgdb_check_in_log $logdir/slgdb_checkin.log

set sl1callpath_build_log $logdir/sl1callpath_build.log
set sl2callpath_build_log $logdir/sl2callpath_build.log
set slcallpath_check_in_log $logdir/slcallpath_checkin.log

set profilelib_build_log $logdir/profilelib_build.log

set soc_sl1_build_log $logdir/socsl1_build.log
set soc_sl1_checkin_log $logdir/socsl1_checkin.log

set objutil_build_log $logdir/objutil_build.log
set objutil_checkin_log $logdir/objutil_checkin.log

set cc  	{}
set cxx 	{}
set fc  	{}
set cflags 	{}
set cxxflags 	{}
set fflags 	{}
set sim         {}
set comp_home 	{}
set sim_home    {}
set lib_home    {}
#set maximum timeout 2 minutes
set max_timeout 120

#ignore these directories
set ignoredirs [list "conf" "dat" "doc" "log" "output"]

set smoking_test_list ""
lappend smoking_test_list "sl1/fsim/fsim_sl1.exp"
lappend smoking_test_list "sl1/compiler/compiler_sl1.exp"
lappend smoking_test_list "sl1/cpp/cpp_sl1.exp"
lappend smoking_test_list "sl2/fsim/fsim_sl2.exp" 
lappend smoking_test_list "sl2/compiler/compiler_sl2.exp"
lappend smoking_test_list "sl2/libtest/libtest_sl2.exp"

# cases listed in pre_test_cases will be run orderly before others
# musted be relative path
set pre_test_list ""
lappend pre_test_list "build_tool/build_tool.exp"

system mkdir -p $logdir
system mkdir -p $testoutput

