/*
 *  File: sl1instrtable.cpp
 * 
 *  Copyright (c) 2006 Beijing SimpLight Nanoelectornics, Ltd.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without modification, 
 *  are permitted provided that the following conditions are met:
 *
 *  1.Redistributions of source code must retain the above copyright notice, 
 *    this list of conditions and the following disclaimer. 
 *  2.Redistributions in binary form must reproduce the above copyright notice, 
 *    this list of conditions and the following disclaimer in the documentation 
 *    and/or other materials provided with the distribution. 
 *
 *  THIS SOFTWARE IS PROVIDED BY THE FREEBSD PROJECT ``AS IS'' AND ANY EXPRESS 
 *  OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 *  IN NO EVENT SHALL THE FREEBSD PROJECT OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
 *  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY 
 *  OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE 
 *  OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED 
 *  OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#include "sl1instrtable.h"
#include "sl1decoder.h"
#include "sl1instrid.h"
#include "sl1disasm.h"
#include "sl1exec.h"

STRING Instr_Group_Name[EIG_max] = {
	"gr",
	"alu",
	"alu16",
	"ls",
	"ls16",
	"br",
	"br16",
	"j",
	"j16",
	"c3_mac",	
	"c3_ffe",
	"c3_viterbi",
	"c3_traceback",
	"misc"
};

//Fsim ISA Header File

//Instruction table definition

class SL1InstrTableEntry Top_Table[0x40] = 
 {
	{"G0", G0_id, 0, EIG_gr, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"G1", G1_id, 0, EIG_gr, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"G2", G2_id, 0, EIG_gr, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"C1", C1_id, 0, EIG_gr, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"C3", C3_id, 0, EIG_gr, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"C4", C4_id, 0, EIG_gr, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"add.i", addi_id, 1, EIG_alu, &SL1Decoder::decodeCore01_01, &SL1Exec::execAddi, &SL1Disasm::disasmCore01_01},
	{"and.i", andi_id, 1, EIG_alu, &SL1Decoder::decodeCore01_06, &SL1Exec::execAndi, &SL1Disasm::disasmCore01_06},
	{"br.eq", breq_id, 1, EIG_br, &SL1Decoder::decodeCore01_07, &SL1Exec::execBreq, &SL1Disasm::disasmCore01_07},
	{"br.ne", brne_id, 1, EIG_br, &SL1Decoder::decodeCore01_07, &SL1Exec::execBrne, &SL1Disasm::disasmCore01_07},
	{"jp", jp_id, 1, EIG_j, &SL1Decoder::decodeCore01_04, &SL1Exec::execJp, &SL1Disasm::disasmCore01_04},
	{"jp.lnk", jplnk_id, 1, EIG_j, &SL1Decoder::decodeCore01_04, &SL1Exec::execJplnk, &SL1Disasm::disasmCore01_04},
	{"ldb", ldb_id, 1, EIG_ls, &SL1Decoder::decodeCore01_03, &SL1Exec::execLdb, &SL1Disasm::disasmCore01_03},
	{"ldh", ldh_id, 1, EIG_ls, &SL1Decoder::decodeCore01_03, &SL1Exec::execLdh, &SL1Disasm::disasmCore01_03},
	{"ldub", ldub_id, 1, EIG_ls, &SL1Decoder::decodeCore01_03, &SL1Exec::execLdub, &SL1Disasm::disasmCore01_03},
	{"lduh", lduh_id, 1, EIG_ls, &SL1Decoder::decodeCore01_03, &SL1Exec::execLduh, &SL1Disasm::disasmCore01_03},
	{"ldw", ldw_id, 1, EIG_ls, &SL1Decoder::decodeCore01_03, &SL1Exec::execLdw, &SL1Disasm::disasmCore01_03},
	{"mvup.i", mvupi_id, 1, EIG_alu, &SL1Decoder::decodeCore01_05, &SL1Exec::execMvupi, &SL1Disasm::disasmCore01_05},
	{"nor.i", nori_id, 1, EIG_alu, &SL1Decoder::decodeCore01_06, &SL1Exec::execNori, &SL1Disasm::disasmCore01_06},
	{"or.i", ori_id, 1, EIG_alu, &SL1Decoder::decodeCore01_06, &SL1Exec::execOri, &SL1Disasm::disasmCore01_06},
	{"setlt.i", setlti_id, 1, EIG_alu, &SL1Decoder::decodeCore01_01, &SL1Exec::execSetlti, &SL1Disasm::disasmCore01_01},
	{"setltu.i", setltui_id, 1, EIG_alu, &SL1Decoder::decodeCore01_01, &SL1Exec::execSetltui, &SL1Disasm::disasmCore01_01},
	{"stb", stb_id, 1, EIG_ls, &SL1Decoder::decodeCore01_02, &SL1Exec::execStb, &SL1Disasm::disasmCore01_02},
	{"sth", sth_id, 1, EIG_ls, &SL1Decoder::decodeCore01_02, &SL1Exec::execSth, &SL1Disasm::disasmCore01_02},
	{"stw", stw_id, 1, EIG_ls, &SL1Decoder::decodeCore01_02, &SL1Exec::execStw, &SL1Disasm::disasmCore01_02},
	{"xor.i", xori_id, 1, EIG_alu, &SL1Decoder::decodeCore01_06, &SL1Exec::execXori, &SL1Disasm::disasmCore01_06},
	{"add16", add16_id, 1, EIG_alu16, &SL1Decoder::decodeCore02_01, &SL1Exec::execAdd16, &SL1Disasm::disasmCore02_01},
	{"add16.i", add16i_id, 1, EIG_alu16, &SL1Decoder::decodeCore02_05, &SL1Exec::execAdd16i, &SL1Disasm::disasmCore02_05},
	{"and16", and16_id, 1, EIG_alu16, &SL1Decoder::decodeCore02_01, &SL1Exec::execAnd16, &SL1Disasm::disasmCore02_01},
	{"and16.i", and16i_id, 1, EIG_alu16, &SL1Decoder::decodeCore02_05, &SL1Exec::execAnd16i, &SL1Disasm::disasmCore02_05},
	{"ldw16", ldw16_id, 1, EIG_ls16, &SL1Decoder::decodeCore02_08, &SL1Exec::execLdw16, &SL1Disasm::disasmCore02_08},
	{"stw16", stw16_id, 1, EIG_ls16, &SL1Decoder::decodeCore02_09, &SL1Exec::execStw16, &SL1Disasm::disasmCore02_09},
	{"mv16", mv16_id, 1, EIG_alu16, &SL1Decoder::decodeCore02_01, &SL1Exec::execMv16, &SL1Disasm::disasmCore02_01},
	{"mv16.i", mv16i_id, 1, EIG_alu16, &SL1Decoder::decodeCore02_02, &SL1Exec::execMv16i, &SL1Disasm::disasmCore02_02},
	{"or16.i", or16i_id, 1, EIG_alu16, &SL1Decoder::decodeCore02_05, &SL1Exec::execOr16i, &SL1Disasm::disasmCore02_05},
	{"mvfc16", mvfc16_id, 1, EIG_alu16, &SL1Decoder::decodeCore02_06, &SL1Exec::execMvfc16, &SL1Disasm::disasmCore02_06},
	{"or16", or16_id, 1, EIG_alu16, &SL1Decoder::decodeCore02_01, &SL1Exec::execOr16, &SL1Disasm::disasmCore02_01},
	{"mvtc16", mvtc16_id, 1, EIG_alu16, &SL1Decoder::decodeCore02_07, &SL1Exec::execMvtc16, &SL1Disasm::disasmCore02_07},
	{"pop16", pop16_id, 1, EIG_ls16, &SL1Decoder::decodeCore02_10, &SL1Exec::execPop16, &SL1Disasm::disasmCore02_10},
	{"push16", push16_id, 1, EIG_ls16, &SL1Decoder::decodeCore02_11, &SL1Exec::execPush16, &SL1Disasm::disasmCore02_11},
	{"shra16.i", shra16i_id, 1, EIG_alu16, &SL1Decoder::decodeCore02_05, &SL1Exec::execShra16i, &SL1Disasm::disasmCore02_05},
	{"shll16", shll16_id, 1, EIG_alu16, &SL1Decoder::decodeCore02_01, &SL1Exec::execShll16, &SL1Disasm::disasmCore02_01},
	{"shll16.i", shll16i_id, 1, EIG_alu16, &SL1Decoder::decodeCore02_05, &SL1Exec::execShll16i, &SL1Disasm::disasmCore02_05},
	{"br16.eqz", br16eqz_id, 1, EIG_br16, &SL1Decoder::decodeCore02_03, &SL1Exec::execBr16eqz, &SL1Disasm::disasmCore02_03},
	{"br16.nez", br16nez_id, 1, EIG_br16, &SL1Decoder::decodeCore02_03, &SL1Exec::execBr16nez, &SL1Disasm::disasmCore02_03},
	{"shrl16.i", shrl16i_id, 1, EIG_alu16, &SL1Decoder::decodeCore02_05, &SL1Exec::execShrl16i, &SL1Disasm::disasmCore02_05},
	{"sub16", sub16_id, 1, EIG_alu16, &SL1Decoder::decodeCore02_01, &SL1Exec::execSub16, &SL1Disasm::disasmCore02_01},
	{"sub16.i", sub16i_id, 1, EIG_alu16, &SL1Decoder::decodeCore02_05, &SL1Exec::execSub16i, &SL1Disasm::disasmCore02_05},
	{"xor16", xor16_id, 1, EIG_alu16, &SL1Decoder::decodeCore02_01, &SL1Exec::execXor16, &SL1Disasm::disasmCore02_01},
	{"xor16.i", xor16i_id, 1, EIG_alu16, &SL1Decoder::decodeCore02_05, &SL1Exec::execXor16i, &SL1Disasm::disasmCore02_05},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
};

class SL1InstrTableEntry G0_Table[0x40] = 
 {
	{"nop", nop_id, 1, EIG_alu, &SL1Decoder::decodeCore04_01, &SL1Exec::execNop, &SL1Disasm::disasmCore04_01},
	{"add", add_id, 1, EIG_alu, &SL1Decoder::decodeCore04_02, &SL1Exec::execAdd, &SL1Disasm::disasmCore04_02},
	{"and", and_id, 1, EIG_alu, &SL1Decoder::decodeCore04_02, &SL1Exec::execAnd, &SL1Disasm::disasmCore04_02},
	{"depb", depb_id, 1, EIG_alu, &SL1Decoder::decodeCore04_03, &SL1Exec::execDepb, &SL1Disasm::disasmCore04_03},
	{"extrb", extrb_id, 1, EIG_alu, &SL1Decoder::decodeCore04_03, &SL1Exec::execExtrb, &SL1Disasm::disasmCore04_03},
	{"extrbu", extrbu_id, 1, EIG_alu, &SL1Decoder::decodeCore04_03, &SL1Exec::execExtrbu, &SL1Disasm::disasmCore04_03},
	{"mvtc.i", mvtci_id, 1, EIG_alu, &SL1Decoder::decodeCore05_06, &SL1Exec::execMvtci, &SL1Disasm::disasmCore05_06},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"mvfc", mvfc_id, 0, EIG_alu, &SL1Decoder::decodeCore04_06, &SL1Exec::execMvfc, &SL1Disasm::disasmCore04_06},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"mvtc", mvtc_id, 0, EIG_alu, &SL1Decoder::decodeCore04_08, &SL1Exec::execMvtc, &SL1Disasm::disasmCore04_08},
	{"nor", nor_id, 1, EIG_alu, &SL1Decoder::decodeCore04_02, &SL1Exec::execNor, &SL1Disasm::disasmCore04_02},
	{"or", or_id, 1, EIG_alu, &SL1Decoder::decodeCore04_02, &SL1Exec::execOr, &SL1Disasm::disasmCore04_02},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"setlt", setlt_id, 1, EIG_alu, &SL1Decoder::decodeCore04_02, &SL1Exec::execSetlt, &SL1Disasm::disasmCore04_02},
	{"setltu", setltu_id, 1, EIG_alu, &SL1Decoder::decodeCore04_02, &SL1Exec::execSetltu, &SL1Disasm::disasmCore04_02},
	{"shll", shll_id, 1, EIG_alu, &SL1Decoder::decodeCore04_02, &SL1Exec::execShll, &SL1Disasm::disasmCore04_02},
	{"shll.i", shlli_id, 1, EIG_alu, &SL1Decoder::decodeCore04_10, &SL1Exec::execShlli, &SL1Disasm::disasmCore04_10},
	{"shra", shra_id, 1, EIG_alu, &SL1Decoder::decodeCore04_02, &SL1Exec::execShra, &SL1Disasm::disasmCore04_02},
	{"shra.i", shrai_id, 1, EIG_alu, &SL1Decoder::decodeCore04_10, &SL1Exec::execShrai, &SL1Disasm::disasmCore04_10},
	{"shrl", shrl_id, 1, EIG_alu, &SL1Decoder::decodeCore04_02, &SL1Exec::execShrl, &SL1Disasm::disasmCore04_02},
	{"shrl.i", shrli_id, 1, EIG_alu, &SL1Decoder::decodeCore04_10, &SL1Exec::execShrli, &SL1Disasm::disasmCore04_10},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"sub", sub_id, 1, EIG_alu, &SL1Decoder::decodeCore04_02, &SL1Exec::execSub, &SL1Disasm::disasmCore04_02},
	{"xor", xor_id, 1, EIG_alu, &SL1Decoder::decodeCore04_02, &SL1Exec::execXor, &SL1Disasm::disasmCore04_02},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"mc.r.eq", mcreq_id, 1, EIG_alu, &SL1Decoder::decodeCore04_04, &SL1Exec::execMcreq, &SL1Disasm::disasmCore04_04},
	{"mc.r.ne", mcrne_id, 1, EIG_alu, &SL1Decoder::decodeCore04_04, &SL1Exec::execMcrne, &SL1Disasm::disasmCore04_04},
	{"mc.r.gt", mcrgt_id, 1, EIG_alu, &SL1Decoder::decodeCore04_04, &SL1Exec::execMcrgt, &SL1Disasm::disasmCore04_04},
	{"mc.r.ge", mcrge_id, 1, EIG_alu, &SL1Decoder::decodeCore04_04, &SL1Exec::execMcrge, &SL1Disasm::disasmCore04_04},
	{"mc.r.lt", mcrlt_id, 1, EIG_alu, &SL1Decoder::decodeCore04_04, &SL1Exec::execMcrlt, &SL1Disasm::disasmCore04_04},
	{"mc.r.le", mcrle_id, 1, EIG_alu, &SL1Decoder::decodeCore04_04, &SL1Exec::execMcrle, &SL1Disasm::disasmCore04_04},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"mc.zc.eq", mczceq_id, 1, EIG_alu, &SL1Decoder::decodeCore04_04, &SL1Exec::execMczceq, &SL1Disasm::disasmCore04_04},
	{"mc.zc.ne", mczcne_id, 1, EIG_alu, &SL1Decoder::decodeCore04_04, &SL1Exec::execMczcne, &SL1Disasm::disasmCore04_04},
	{"mc.zc.gt", mczcgt_id, 1, EIG_alu, &SL1Decoder::decodeCore04_04, &SL1Exec::execMczcgt, &SL1Disasm::disasmCore04_04},
	{"mc.zc.ge", mczcge_id, 1, EIG_alu, &SL1Decoder::decodeCore04_04, &SL1Exec::execMczcge, &SL1Disasm::disasmCore04_04},
	{"mc.zc.lt", mczclt_id, 1, EIG_alu, &SL1Decoder::decodeCore04_04, &SL1Exec::execMczclt, &SL1Disasm::disasmCore04_04},
	{"mc.zc.le", mczcle_id, 1, EIG_alu, &SL1Decoder::decodeCore04_04, &SL1Exec::execMczcle, &SL1Disasm::disasmCore04_04},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"mc.z.eq", mczeq_id, 1, EIG_alu, &SL1Decoder::decodeCore04_04, &SL1Exec::execMczeq, &SL1Disasm::disasmCore04_04},
	{"mc.z.ne", mczne_id, 1, EIG_alu, &SL1Decoder::decodeCore04_04, &SL1Exec::execMczne, &SL1Disasm::disasmCore04_04},
	{"mc.z.gt", mczgt_id, 1, EIG_alu, &SL1Decoder::decodeCore04_04, &SL1Exec::execMczgt, &SL1Disasm::disasmCore04_04},
	{"mc.z.ge", mczge_id, 1, EIG_alu, &SL1Decoder::decodeCore04_04, &SL1Exec::execMczge, &SL1Disasm::disasmCore04_04},
	{"mc.z.lt", mczlt_id, 1, EIG_alu, &SL1Decoder::decodeCore04_04, &SL1Exec::execMczlt, &SL1Disasm::disasmCore04_04},
	{"mc.z.le", mczle_id, 1, EIG_alu, &SL1Decoder::decodeCore04_04, &SL1Exec::execMczle, &SL1Disasm::disasmCore04_04},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"mc.zn.eq", mczneq_id, 1, EIG_alu, &SL1Decoder::decodeCore04_04, &SL1Exec::execMczneq, &SL1Disasm::disasmCore04_04},
	{"mc.zn.ne", mcznne_id, 1, EIG_alu, &SL1Decoder::decodeCore04_04, &SL1Exec::execMcznne, &SL1Disasm::disasmCore04_04},
	{"mc.zn.gt", mczngt_id, 1, EIG_alu, &SL1Decoder::decodeCore04_04, &SL1Exec::execMczngt, &SL1Disasm::disasmCore04_04},
	{"mc.zn.ge", mcznge_id, 1, EIG_alu, &SL1Decoder::decodeCore04_04, &SL1Exec::execMcznge, &SL1Disasm::disasmCore04_04},
	{"mc.zn.lt", mcznlt_id, 1, EIG_alu, &SL1Decoder::decodeCore04_04, &SL1Exec::execMcznlt, &SL1Disasm::disasmCore04_04},
	{"mc.zn.le", mcznle_id, 1, EIG_alu, &SL1Decoder::decodeCore04_04, &SL1Exec::execMcznle, &SL1Disasm::disasmCore04_04},
	{"mc.abs", mcabs_id, 1, EIG_alu, &SL1Decoder::decodeCore04_05, &SL1Exec::execMcabs, &SL1Disasm::disasmCore04_05},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
};

class SL1InstrTableEntry G1_Table[0x20] = 
 {
	{"br.gez", brgez_id, 1, EIG_br, &SL1Decoder::decodeCore05_01, &SL1Exec::execBrgez, &SL1Disasm::disasmCore05_01},
	{"br.gtz", brgtz_id, 1, EIG_br, &SL1Decoder::decodeCore05_01, &SL1Exec::execBrgtz, &SL1Disasm::disasmCore05_01},
	{"br.lez", brlez_id, 1, EIG_br, &SL1Decoder::decodeCore05_01, &SL1Exec::execBrlez, &SL1Disasm::disasmCore05_01},
	{"br.ltz", brltz_id, 1, EIG_br, &SL1Decoder::decodeCore05_01, &SL1Exec::execBrltz, &SL1Disasm::disasmCore05_01},
	{"break", break_id, 0, EIG_misc, &SL1Decoder::decodeUndefined, &SL1Exec::execBreak, &SL1Disasm::disasmUndefined},
	{"dcflush", dcflush_id, 1, EIG_misc, &SL1Decoder::decodeCore05_01, &SL1Exec::execDcflush, &SL1Disasm::disasmCore05_01},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"ret", ret_id, 0, EIG_j, &SL1Decoder::decodeCore05_02, &SL1Exec::execRet, &SL1Disasm::disasmCore05_02},
	{"rete", rete_id, 0, EIG_j, &SL1Decoder::decodeCore05_02, &SL1Exec::execRete, &SL1Disasm::disasmCore05_02},
	{"syscall", syscall_id, 1, EIG_j, &SL1Decoder::decodeCore05_03, &SL1Exec::execSyscall, &SL1Disasm::disasmCore05_03},
	{"jr", jr_id, 0, EIG_j, &SL1Decoder::decodeCore05_05, &SL1Exec::execJr, &SL1Disasm::disasmCore05_05},
	{"jr.lnk", jrlnk_id, 0, EIG_j, &SL1Decoder::decodeCore05_05, &SL1Exec::execJrlnk, &SL1Disasm::disasmCore05_05},
	{"loop", loop_id, 1, EIG_alu, &SL1Decoder::decodeCore05_04, &SL1Exec::execLoop, &SL1Disasm::disasmCore05_04},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
};

class SL1InstrTableEntry G2_Table[0x20] = 
 {
	{"nop16", nop16_id, 1, EIG_alu16, &SL1Decoder::decodeCore03_01, &SL1Exec::execNop16, &SL1Disasm::disasmCore03_01},
	{"rete16", rete16_id, 1, EIG_j16, &SL1Decoder::decodeCore03_04, &SL1Exec::execRete16, &SL1Disasm::disasmCore03_04},
	{"break16", break16_id, 1, EIG_j16, &SL1Decoder::decodeCore03_04, &SL1Exec::execBreak16, &SL1Disasm::disasmCore03_04},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"abs16", abs16_id, 1, EIG_alu16, &SL1Decoder::decodeCore03_02, &SL1Exec::execAbs16, &SL1Disasm::disasmCore03_02},
	{"jr16", jr16_id, 1, EIG_j16, &SL1Decoder::decodeCore03_01, &SL1Exec::execJr16, &SL1Disasm::disasmCore03_01},
	{"jr16.lnk", jr16lnk_id, 1, EIG_j16, &SL1Decoder::decodeCore03_01, &SL1Exec::execJr16lnk, &SL1Disasm::disasmCore03_01},
	{"ret16", ret16_id, 1, EIG_j16, &SL1Decoder::decodeCore03_04, &SL1Exec::execRet16, &SL1Disasm::disasmCore03_04},
	{"inv16", inv16_id, 1, EIG_alu16, &SL1Decoder::decodeCore03_02, &SL1Exec::execInv16, &SL1Disasm::disasmCore03_02},
	{"ldub16.rs", ldub16rs_id, 1, EIG_ls16, &SL1Decoder::decodeCore03_02, &SL1Exec::execLdub16rs, &SL1Disasm::disasmCore03_02},
	{"lduh16.rs", lduh16rs_id, 1, EIG_ls16, &SL1Decoder::decodeCore03_02, &SL1Exec::execLduh16rs, &SL1Disasm::disasmCore03_02},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"add16.sp", add16sp_id, 1, EIG_alu16, &SL1Decoder::decodeCore03_03, &SL1Exec::execAdd16sp, &SL1Disasm::disasmCore03_03},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
};

class SL1InstrTableEntry C2_Table[0x40] = 
 {
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
};


class SL1InstrTableEntry C3_Table[0x40] = 
 {
	{"c3.saadds", c3saadds_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_01, &SL1Exec::execC3saadds, &SL1Disasm::disasmBb_01},
	{"c3.saadd.a", c3saadda_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_02, &SL1Exec::execC3saadda, &SL1Disasm::disasmBb_02},
	{"c3.aadda", c3aadda_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_03, &SL1Exec::execC3aadda, &SL1Disasm::disasmBb_03},
	{"c3.bitr", c3bitr_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_05, &SL1Exec::execC3bitr, &SL1Disasm::disasmBb_05},
	{"c3.sadda", c3sadda_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_06, &SL1Exec::execC3sadda, &SL1Disasm::disasmBb_06},
	{"c3.sadda.a", c3saddaa_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_07, &SL1Exec::execC3saddaa, &SL1Disasm::disasmBb_07},
	{"c3.ld", c3ld_id, 8, EIG_ls, &SL1Decoder::decodeBb_08, &SL1Exec::execC3ld, &SL1Disasm::disasmBb_08},
	{"c3.shav", c3shav_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_04, &SL1Exec::execC3shav, &SL1Disasm::disasmBb_04},
	{"c3.mac", c3mac_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_09, &SL1Exec::execC3mac, &SL1Disasm::disasmBb_09},
	{"c3.mac.a", c3maca_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_10, &SL1Exec::execC3maca, &SL1Disasm::disasmBb_10},
	{"c3.mac.ar", c3macar_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_11, &SL1Exec::execC3macar, &SL1Disasm::disasmBb_11},
	{"c3.mac.i", c3maci_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_12, &SL1Exec::execC3maci, &SL1Disasm::disasmBb_12},
	{"c3.samulsh", c3samulsh_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_01, &SL1Exec::execC3samulsh, &SL1Disasm::disasmBb_01},
	{"c3.samulh.a", c3samulha_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_02, &SL1Exec::execC3samulha, &SL1Disasm::disasmBb_02},
	{"c3.shla.i", c3shlai_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_13, &SL1Exec::execC3shlai, &SL1Disasm::disasmBb_13},
	{"c3.shlafa.i", c3shlafai_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_14, &SL1Exec::execC3shlafai, &SL1Disasm::disasmBb_14},
	{"c3.shrafa.i", c3shrafai_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_14, &SL1Exec::execC3shrafai, &SL1Disasm::disasmBb_14},
	{"c3.shra.i", c3shrai_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_13, &SL1Exec::execC3shrai, &SL1Disasm::disasmBb_13},
	{"c3.macn", c3macn_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_09, &SL1Exec::execC3macn, &SL1Disasm::disasmBb_09},
	{"c3.macn.a", c3macna_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_10, &SL1Exec::execC3macna, &SL1Disasm::disasmBb_10},
	{"c3.macn.ar", c3macnar_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_11, &SL1Exec::execC3macnar, &SL1Disasm::disasmBb_11},
	{"c3.macn.i", c3macni_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_12, &SL1Exec::execC3macni, &SL1Disasm::disasmBb_12},
	{"c3.mula", c3mula_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_15, &SL1Exec::execC3mula, &SL1Disasm::disasmBb_15},
	{"c3.mula.a", c3mulaa_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_16, &SL1Exec::execC3mulaa, &SL1Disasm::disasmBb_16},
	{"c3.mula.ar", c3mulaar_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_17, &SL1Exec::execC3mulaar, &SL1Disasm::disasmBb_17},	
	{"c3.mula.i", c3mulai_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_18, &SL1Exec::execC3mulai, &SL1Disasm::disasmBb_18},
	{"c3.shlata.i", c3shlatai_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_19, &SL1Exec::execC3shlatai, &SL1Disasm::disasmBb_19},
	{"c3.shrata.i", c3shratai_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_19, &SL1Exec::execC3shratai, &SL1Disasm::disasmBb_19},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
	{"c3.nega", c3nega_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_38, &SL1Exec::execC3nega, &SL1Disasm::disasmBb_38},
	{"c3.mulan", c3mulan_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_15, &SL1Exec::execC3mulan, &SL1Disasm::disasmBb_15},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},	
	{"c3.lead", c3lead_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_20, &SL1Exec::execC3lead, &SL1Disasm::disasmBb_20},
	{"c3.mvfs", c3mvfs_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_21, &SL1Exec::execC3mvfs, &SL1Disasm::disasmBb_21},
	{"c3.mvts", c3mvts_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_22, &SL1Exec::execC3mvts, &SL1Disasm::disasmBb_22},
	{"c3.dmac", c3dmac_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_23, &SL1Exec::execC3dmac, &SL1Disasm::disasmBb_23},
	{"c3.dmacn", c3dmacn_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_23, &SL1Exec::execC3dmacn, &SL1Disasm::disasmBb_23},
	{"c3.dmac.a", c3dmaca_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_24, &SL1Exec::execC3dmaca, &SL1Disasm::disasmBb_24},
	{"c3.dmacn.a", c3dmacna_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_24, &SL1Exec::execC3dmacna, &SL1Disasm::disasmBb_24},
	{"c3.dadd", c3dadd_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_25, &SL1Exec::execC3dadd, &SL1Disasm::disasmBb_25},
	{"c3.dsub", c3dsub_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_25, &SL1Exec::execC3dsub, &SL1Disasm::disasmBb_25},
	{"c3.revb", c3revb_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_26, &SL1Exec::execC3revb, &SL1Disasm::disasmBb_26},
	{"c3.round", c3round_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_27, &SL1Exec::execC3round, &SL1Disasm::disasmBb_27},	
	{"c3.dmula", c3dmula_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_28, &SL1Exec::execC3dmula, &SL1Disasm::disasmBb_28},
	{"c3.dmulan", c3dmulan_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_28, &SL1Exec::execC3dmulan, &SL1Disasm::disasmBb_28},
	{"c3.dmula.a", c3dmulaa_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_29, &SL1Exec::execC3dmulaa, &SL1Disasm::disasmBb_29},
	{"c3.dmulan.a", c3dmulana_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_29, &SL1Exec::execC3dmulana, &SL1Disasm::disasmBb_29},
	{"c3.fftld", c3fftld_id, 8, EIG_ls, &SL1Decoder::decodeBb_30, &SL1Exec::execC3fftld, &SL1Disasm::disasmBb_30},
	{"c3.fftst", c3fftst_id, 8, EIG_ls, &SL1Decoder::decodeBb_31, &SL1Exec::execC3fftst, &SL1Disasm::disasmBb_31},
	{"c3.subc", c3subc_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_32, &SL1Exec::execC3subc, &SL1Disasm::disasmBb_32},
	{"c3.cs", c3cs_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_33, &SL1Exec::execC3cs, &SL1Disasm::disasmBb_33},
	{"c3.dshll.i", c3dshlli_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_34, &SL1Exec::execC3dshlli, &SL1Disasm::disasmBb_34},
	{"c3.dshrl.i", c3dshrli_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_34, &SL1Exec::execC3dshrli, &SL1Disasm::disasmBb_34},
	{"c3.st", c3st_id, 8, EIG_ls, &SL1Decoder::decodeBb_35, &SL1Exec::execC3st, &SL1Disasm::disasmBb_35},
	{"c3.sasubsh", c3sasubsh_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_01, &SL1Exec::execC3sasubsh, &SL1Disasm::disasmBb_01},
	{"c3.sasub.a", c3sasuba_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_02, &SL1Exec::execC3sasuba, &SL1Disasm::disasmBb_02},
	{"c3.muls", c3muls_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_36, &SL1Exec::execC3muls, &SL1Disasm::disasmBb_36},
	{"c3.mulus", c3mulus_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_36, &SL1Exec::execC3mulus, &SL1Disasm::disasmBb_36},
	{"c3.saaddh.a", c3saaddha_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_02, &SL1Exec::execC3saaddha, &SL1Disasm::disasmBb_02},
	{"c3.sasubh.a", c3sasubha_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_02, &SL1Exec::execC3sasubha, &SL1Disasm::disasmBb_02},
	{"c3.saaddsh", c3saaddsh_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_01, &SL1Exec::execC3saaddsh, &SL1Disasm::disasmBb_01},
	{"c3.sasubs", c3sasubs_id, 8, EIG_c3_mac, &SL1Decoder::decodeBb_01, &SL1Exec::execC3sasubs, &SL1Disasm::disasmBb_01},
	{"c3.ffe", c3ffe_id, 8, EIG_c3_ffe, &SL1Decoder::decodeBb_37, &SL1Exec::execC3ffe, &SL1Disasm::disasmBb_37},
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
};
class SL1InstrTableEntry Invalid_Table[] = {
	{"illegal", illegal_id, 0, EIG_invalid, &SL1Decoder::decodeUndefined, &SL1Exec::execInvalid, &SL1Disasm::disasmUndefined},
};

