/* THIS FILE IS AUTOMATICALLY GENERATED BY table */

#include "string_utils.h"

#include "options.h"
#include "option_seen.h"
#include "option_names.h"
#include "opt_actions.h"
#include "get_options.h"

#include "errors.h"
extern void
toggle_implicits (void)
{
	if (option_was_implicitly_seen(O_woffall)) {
		option_name = get_option_name(O_woffall);
		toggle(&msglevel,0);
	}
	if (option_was_implicitly_seen(O_w)) {
		option_name = get_option_name(O_w);
		toggle(&msglevel,0);
	}
	if (option_was_implicitly_seen(O_useas)) {
		option_name = get_option_name(O_useas);
		toggle(&skip_as,FALSE);
	}
	if (option_was_implicitly_seen(O_shared)) {
		option_name = get_option_name(O_shared);
		toggle(&shared,DSO_SHARED);
	}
	if (option_was_implicitly_seen(O_r8)) {
		option_name = get_option_name(O_r8);
		toggle(&rflag,2);
	}
	if (option_was_implicitly_seen(O_r4)) {
		option_name = get_option_name(O_r4);
		toggle(&rflag,1);
	}
	if (option_was_implicitly_seen(O_r)) {
		option_name = get_option_name(O_r);
		toggle(&shared,RELOCATABLE);last_phase=P_any_ld;
	}
	if (option_was_implicitly_seen(O_noi4)) {
		option_name = get_option_name(O_noi4);
		toggle(&iflag,1);
	}
	if (option_was_implicitly_seen(O_noas)) {
		option_name = get_option_name(O_noas);
		toggle(&skip_as,TRUE);
	}
	if (option_was_implicitly_seen(O_mxop)) {
		option_name = get_option_name(O_mxop);
		toggle(&sse2,TRUE);toggle(&xop,TRUE);
	}
	if (option_was_implicitly_seen(O_mssse3)) {
		option_name = get_option_name(O_mssse3);
		toggle(&sse2,TRUE);toggle(&ssse3,TRUE);
	}
	if (option_was_implicitly_seen(O_msse4a)) {
		option_name = get_option_name(O_msse4a);
		toggle(&sse2,TRUE);toggle(&sse4a,TRUE);
	}
	if (option_was_implicitly_seen(O_msse42)) {
		option_name = get_option_name(O_msse42);
		toggle(&sse2,TRUE);toggle(&sse42,TRUE);
	}
	if (option_was_implicitly_seen(O_msse41)) {
		option_name = get_option_name(O_msse41);
		toggle(&sse2,TRUE);toggle(&sse41,TRUE);
	}
	if (option_was_implicitly_seen(O_msse3)) {
		option_name = get_option_name(O_msse3);
		toggle(&sse2,TRUE);toggle(&sse3,TRUE);
	}
	if (option_was_implicitly_seen(O_msse2)) {
		option_name = get_option_name(O_msse2);
		toggle(&mmx,TRUE);toggle(&sse,TRUE);toggle(&sse2,TRUE);
	}
	if (option_was_implicitly_seen(O_msse)) {
		option_name = get_option_name(O_msse);
		toggle(&mmx,TRUE);toggle(&sse,TRUE);
	}
	if (option_was_implicitly_seen(O_mspace)) {
		option_name = get_option_name(O_mspace);
		toggle(&ospace,TRUE);
	}
	if (option_was_implicitly_seen(O_mso)) {
		option_name = get_option_name(O_mso);
		toggle(&oscale,TRUE);
	}
	if (option_was_implicitly_seen(O_mpclmul)) {
		option_name = get_option_name(O_mpclmul);
		toggle(&sse2,TRUE);toggle(&pclmul,TRUE);
	}
	if (option_was_implicitly_seen(O_mp)) {
		option_name = get_option_name(O_mp);
		toggle(&mpkind,NORMAL_MP);
	}
	if (option_was_implicitly_seen(O_mno_xop)) {
		option_name = get_option_name(O_mno_xop);
		toggle(&xop,FALSE);
	}
	if (option_was_implicitly_seen(O_mno_ssse3)) {
		option_name = get_option_name(O_mno_ssse3);
		toggle(&ssse3,FALSE);
	}
	if (option_was_implicitly_seen(O_mno_sse4a)) {
		option_name = get_option_name(O_mno_sse4a);
		toggle(&sse4a,FALSE);
	}
	if (option_was_implicitly_seen(O_mno_sse42)) {
		option_name = get_option_name(O_mno_sse42);
		toggle(&sse42,FALSE);
	}
	if (option_was_implicitly_seen(O_mno_sse41)) {
		option_name = get_option_name(O_mno_sse41);
		toggle(&sse41,FALSE);
	}
	if (option_was_implicitly_seen(O_mno_sse3)) {
		option_name = get_option_name(O_mno_sse3);
		toggle(&sse3,FALSE);
	}
	if (option_was_implicitly_seen(O_mno_sse2)) {
		option_name = get_option_name(O_mno_sse2);
		toggle(&sse2,FALSE);toggle(&sse3,FALSE);toggle(&sse4a,FALSE);
	}
	if (option_was_implicitly_seen(O_mno_sse)) {
		option_name = get_option_name(O_mno_sse);
		toggle(&sse,FALSE);toggle(&sse2,FALSE);toggle(&sse3,FALSE);toggle(&sse4a,FALSE);
	}
	if (option_was_implicitly_seen(O_mno_pclmul)) {
		option_name = get_option_name(O_mno_pclmul);
		toggle(&pclmul,FALSE);
	}
	if (option_was_implicitly_seen(O_mno_mmx)) {
		option_name = get_option_name(O_mno_mmx);
		toggle(&mmx,FALSE);toggle(&sse,FALSE);toggle(&sse2,FALSE);toggle(&sse3,FALSE);toggle(&sse4a,FALSE);
	}
	if (option_was_implicitly_seen(O_mno_fma4)) {
		option_name = get_option_name(O_mno_fma4);
		toggle(&fma4,FALSE);
	}
	if (option_was_implicitly_seen(O_mno_avx)) {
		option_name = get_option_name(O_mno_avx);
		toggle(&avx,FALSE);
	}
	if (option_was_implicitly_seen(O_mno_aes)) {
		option_name = get_option_name(O_mno_aes);
		toggle(&aes,FALSE);
	}
	if (option_was_implicitly_seen(O_mno_3dnow)) {
		option_name = get_option_name(O_mno_3dnow);
		toggle(&m3dnow,FALSE);
	}
	if (option_was_implicitly_seen(O_mmmx)) {
		option_name = get_option_name(O_mmmx);
		toggle(&mmx,TRUE);
	}
	if (option_was_implicitly_seen(O_mipslibs)) {
		option_name = get_option_name(O_mipslibs);
		toggle(&use_mipslibs,TRUE);toggle(&use_craylibs,FALSE);
	}
	if (option_was_implicitly_seen(O_mfma4)) {
		option_name = get_option_name(O_mfma4);
		toggle(&sse2,TRUE);toggle(&fma4,TRUE);
	}
	if (option_was_implicitly_seen(O_mavx)) {
		option_name = get_option_name(O_mavx);
		toggle(&sse2,TRUE);toggle(&avx,TRUE);
	}
	if (option_was_implicitly_seen(O_maes)) {
		option_name = get_option_name(O_maes);
		toggle(&sse2,TRUE);toggle(&aes,TRUE);
	}
	if (option_was_implicitly_seen(O_m64)) {
		option_name = get_option_name(O_m64);
		toggle(&abi,ABI_64);
	}
	if (option_was_implicitly_seen(O_m3dnow)) {
		option_name = get_option_name(O_m3dnow);
		toggle(&m3dnow,TRUE);
	}
	if (option_was_implicitly_seen(O_m32)) {
		option_name = get_option_name(O_m32);
		toggle(&abi,ABI_N32);
	}
	if (option_was_implicitly_seen(O_itanium)) {
		option_name = get_option_name(O_itanium);
		toggle(&isa,ISA_IA641);
	}
	if (option_was_implicitly_seen(O_ipa)) {
		option_name = get_option_name(O_ipa);
		toggle(&ipa,TRUE);
	}
	if (option_was_implicitly_seen(O_ia32)) {
		option_name = get_option_name(O_ia32);
		toggle(&abi,ABI_IA32);
	}
	if (option_was_implicitly_seen(O_i8)) {
		option_name = get_option_name(O_i8);
		toggle(&iflag,3);
	}
	if (option_was_implicitly_seen(O_i64)) {
		option_name = get_option_name(O_i64);
		toggle(&abi,ABI_I64);
	}
	if (option_was_implicitly_seen(O_i4)) {
		option_name = get_option_name(O_i4);
		toggle(&iflag,2);
	}
	if (option_was_implicitly_seen(O_i32)) {
		option_name = get_option_name(O_i32);
		toggle(&abi,ABI_I32);
	}
	if (option_was_implicitly_seen(O_i2)) {
		option_name = get_option_name(O_i2);
		toggle(&iflag,1);
	}
	if (option_was_implicitly_seen(O_gnu42)) {
		option_name = get_option_name(O_gnu42);
		toggle(&gnu_major_version,4);toggle(&gnu_minor_version,2);
	}
	if (option_was_implicitly_seen(O_gnu40)) {
		option_name = get_option_name(O_gnu40);
		toggle(&gnu_major_version,4);toggle(&gnu_minor_version,0);
	}
	if (option_was_implicitly_seen(O_gnu4)) {
		option_name = get_option_name(O_gnu4);
		toggle(&gnu_major_version,4);toggle(&gnu_minor_version,2);
	}
	if (option_was_implicitly_seen(O_gnu3)) {
		option_name = get_option_name(O_gnu3);
		toggle(&gnu_major_version,3);toggle(&gnu_minor_version,3);
	}
	if (option_was_implicitly_seen(O_ggdb3)) {
		option_name = get_option_name(O_ggdb3);
		toggle(&glevel,3);
	}
	if (option_was_implicitly_seen(O_ggdb)) {
		option_name = get_option_name(O_ggdb);
		toggle(&glevel,2);
	}
	if (option_was_implicitly_seen(O_gdwarf_23)) {
		option_name = get_option_name(O_gdwarf_23);
		toggle(&glevel,3);
	}
	if (option_was_implicitly_seen(O_gdwarf_22)) {
		option_name = get_option_name(O_gdwarf_22);
		toggle(&glevel,2);
	}
	if (option_was_implicitly_seen(O_gdwarf_21)) {
		option_name = get_option_name(O_gdwarf_21);
		toggle(&glevel,1);
	}
	if (option_was_implicitly_seen(O_gdwarf_20)) {
		option_name = get_option_name(O_gdwarf_20);
		toggle(&glevel,0);
	}
	if (option_was_implicitly_seen(O_gdwarf_2)) {
		option_name = get_option_name(O_gdwarf_2);
		toggle(&glevel,2);
	}
	if (option_was_implicitly_seen(O_g3)) {
		option_name = get_option_name(O_g3);
		toggle(&glevel,3);
	}
	if (option_was_implicitly_seen(O_g2)) {
		option_name = get_option_name(O_g2);
		toggle(&glevel,2);
	}
	if (option_was_implicitly_seen(O_g1)) {
		option_name = get_option_name(O_g1);
		toggle(&glevel,1);
	}
	if (option_was_implicitly_seen(O_g0)) {
		option_name = get_option_name(O_g0);
		toggle(&glevel,0);
	}
	if (option_was_implicitly_seen(O_g)) {
		option_name = get_option_name(O_g);
		toggle(&glevel,2);
	}
	if (option_was_implicitly_seen(O_fullwarn)) {
		option_name = get_option_name(O_fullwarn);
		toggle(&msglevel,2);
	}
	if (option_was_implicitly_seen(O_ftpp)) {
		option_name = get_option_name(O_ftpp);
		toggle(&use_ftpp,1);
	}
	if (option_was_implicitly_seen(O_freeform)) {
		option_name = get_option_name(O_freeform);
		toggle(&fortran_form,2);
	}
	if (option_was_implicitly_seen(O_fpic)) {
		option_name = get_option_name(O_fpic);
		toggle(&pic,TRUE);
	}
	if (option_was_implicitly_seen(O_fno_pic)) {
		option_name = get_option_name(O_fno_pic);
		toggle(&pic,TRUE);
	}
	if (option_was_implicitly_seen(O_fno_math_errno)) {
		option_name = get_option_name(O_fno_math_errno);
		toggle(&fmath_errno,0);
	}
	if (option_was_implicitly_seen(O_fno_fast_math)) {
		option_name = get_option_name(O_fno_fast_math);
		toggle(&ffast_math,0);
	}
	if (option_was_implicitly_seen(O_fno_cxx_openmp)) {
		option_name = get_option_name(O_fno_cxx_openmp);
		toggle(&fcxx_openmp,0);
	}
	if (option_was_implicitly_seen(O_fno_builtin)) {
		option_name = get_option_name(O_fno_builtin);
		toggle(&fbuiltin,0);
	}
	if (option_was_implicitly_seen(O_fno_PIC)) {
		option_name = get_option_name(O_fno_PIC);
		toggle(&pic,TRUE);
	}
	if (option_was_implicitly_seen(O_fmath_errno)) {
		option_name = get_option_name(O_fmath_errno);
		toggle(&fmath_errno,1);
	}
	if (option_was_implicitly_seen(O_fixedform)) {
		option_name = get_option_name(O_fixedform);
		toggle(&fortran_form,1);
	}
	if (option_was_implicitly_seen(O_ffast_math)) {
		option_name = get_option_name(O_ffast_math);
		toggle(&ffast_math,1);
	}
	if (option_was_implicitly_seen(O_fcxx_openmp)) {
		option_name = get_option_name(O_fcxx_openmp);
		toggle(&fcxx_openmp,1);
	}
	if (option_was_implicitly_seen(O_fcoco)) {
		option_name = get_option_name(O_fcoco);
		toggle(&use_coco,TRUE);
	}
	if (option_was_implicitly_seen(O_fbuiltin)) {
		option_name = get_option_name(O_fbuiltin);
		toggle(&fbuiltin,1);
	}
	if (option_was_implicitly_seen(O_fPIC)) {
		option_name = get_option_name(O_fPIC);
		toggle(&pic,TRUE);
	}
	if (option_was_implicitly_seen(O_external_gcc)) {
		option_name = get_option_name(O_external_gcc);
		toggle(&external_gcc,TRUE);
	}
	if (option_was_implicitly_seen(O_d8)) {
		option_name = get_option_name(O_d8);
		toggle(&dflag,1);
	}
	if (option_was_implicitly_seen(O_craylibs)) {
		option_name = get_option_name(O_craylibs);
		toggle(&use_craylibs,TRUE);toggle(&use_mipslibs,FALSE);
	}
	if (option_was_implicitly_seen(O_cpp)) {
		option_name = get_option_name(O_cpp);
		toggle(&use_ftpp,0);first_phase=P_any_cpp;
	}
	if (option_was_implicitly_seen(O_cord)) {
		option_name = get_option_name(O_cord);
		toggle(&cordflag,TRUE);
	}
	if (option_was_implicitly_seen(O_compat_gcc)) {
		option_name = get_option_name(O_compat_gcc);
		toggle(&compat_gcc,TRUE);
	}
	if (option_was_implicitly_seen(O_call_shared)) {
		option_name = get_option_name(O_call_shared);
		toggle(&shared,CALL_SHARED);
	}
	if (option_was_implicitly_seen(O_byteswapio)) {
		option_name = get_option_name(O_byteswapio);
		toggle(&io_byteswap,1);
	}
	if (option_was_implicitly_seen(O_automatic)) {
		option_name = get_option_name(O_automatic);
		toggle(&isstatic,1);
	}
	if (option_was_implicitly_seen(O_ansi)) {
		option_name = get_option_name(O_ansi);
		toggle(&ansi,STRICT_ANSI);
	}
	if (option_was_implicitly_seen(O_Os)) {
		option_name = get_option_name(O_Os);
		toggle(&ospace,TRUE);
	}
	if (option_was_implicitly_seen(O_O2)) {
		option_name = get_option_name(O_O2);
		toggle(&olevel,2);
	}
	if (option_was_implicitly_seen(O_O1)) {
		option_name = get_option_name(O_O1);
		toggle(&olevel,1);
	}
	if (option_was_implicitly_seen(O_O0)) {
		option_name = get_option_name(O_O0);
		toggle(&olevel,0);
	}
	if (option_was_implicitly_seen(O_O)) {
		option_name = get_option_name(O_O);
		toggle(&olevel,2);
	}
	if (option_was_implicitly_seen(O_LANG_std)) {
		option_name = get_option_name(O_LANG_std);
		toggle(&standard_cplusplus,TRUE);
	}
	if (option_was_implicitly_seen(O_IPA_)) {
		option_name = get_option_name(O_IPA_);
		toggle(&ipa,TRUE);
	}
	if (option_was_implicitly_seen(O_IPA)) {
		option_name = get_option_name(O_IPA);
		toggle(&ipa,TRUE);
	}
}

