PSC_NAME_PREFIX=o

PSC_MAJOR_VERSION=2
PSC_MINOR_VERSION=0
PSC_PATCH_LEVEL=0

PSC_FULL_VERSION=${PSC_MAJOR_VERSION}.${PSC_MINOR_VERSION}.${PSC_PATCH_LEVEL}

PSC_GCC_VERSION=3.3.1
PSC_ROOT_PREFIX=/proj/osprey
PSC_INSTALL_PREFIX=/proj/osprey
PSC_INCLUDE_DIR=/usr/include
PSC_TARGET=ia64-hp-linux
