#! /bin/csh

# Clobber everything except ptools-controlled files
set     SRC_DIR         = ../cygnus

rm -rf [a-z]*
rm -f  Makefile
rm -f  ${SRC_DIR}/bfd/po/*.gmo ${SRC_DIR}/opcodes/po/*.gmo ${SRC_DIR}/ld/po/*.gmo
