#!/bin/sh 
#
#       invoke cygnus configure to set up this directory as an
#       ia32-host ia64-target build area
#

#CFLAGS=" -g -I$TARG_ISA_INCLUDE -I$SGIDEFS_INCLUDE
#export CFLAGS
export CFLAGS=" -g -O0 -fno-exceptions -ffloat-store -D__MIPS_AND_IA64_ELF_H"

SRC_DIR=../cygnus
INSTALL_DIR=/usr/ia64-sgi-linux
CONFIGURE=${SRC_DIR}/configure
HOST=ia64-linux-gnu
BUILD=ia64-linux-gnu
TARG=ia64-linux-gnu

${CONFIGURE}                   \
    --srcdir=${SRC_DIR}        \
    --prefix=${INSTALL_DIR}    \
    --host=${HOST}             \
    --target=${TARG}
