#!/bin/sh

# Clobber everything excpet the CONFIGURE FILE
rm -rf build-*-linux-gnu libcpp fixincludes libiberty gcc intl libdecnumber
rm -f libgspin*.a
rm -f config.cache config.log config.status serdep.tmp Makefile

